### DISCUSSION TITLE
crdb container failed with exit code 159 on rpi (/arm/v8)

### DISCUSSION THREAD

**Discussion by masoncole1994** [cockroachdb/cockroach#110398] [Q&A]
Hi all,

I've came with a problem from another disssution, https://github.com/zitadel/zitadel/discussions/6527

I'm trying  to launch a docker-compose file like this, on rasberry pi v4, but crdb container exit with a code 159

Actually, I've tried to research the issue - and it may be related to cpu architecture, when os reports itself as x32.  But I suppose I'm just confused with all this arm cpu 

```yaml
version: '3.8'

services:
  zitadel:
    # restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    platform: linux/arm64
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    # restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.2.2'
    platform: linux/arm64
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

networks:
  zitadel:
```
