### DISCUSSION TITLE
How to use Cockroach as Github Action's Container Service?

### DISCUSSION THREAD

**Discussion by keinsell** [cockroachdb/cockroach#83749] [Q&A] [answered]
I wondering how to include `cockroach` into my pipeline as service, there we don't have option to provide startup command, is there any workaround which will allow me to start `single-node` service for pipeline purposes?

```yml
    services:
      cockroach:
        image: cockroachdb/cockroach:latest
        options: --entrypoint "/cockroach/cockroach.sh start-single-node --insecure"
        ports:
          - 26257:26257
```

**Comment by keinsell** [comment]
Resolved my issue by usage of `timveil/cockroachdb-single-node:latest` instead `cockroachdb/cockroach:latest` which doesn't require command after provided image. It's probably not a solution I wanted but it seems like problem with `GitHub Actions` instead `cockroach` itself.

**Comment by Shinigami92** [comment]
I have the same issue but cannot use `timveil` because they dont use tags

Here is what I tried so far: https://github.com/salsita/node-pg-migrate/pull/968

**Comment by shawntoffel** [comment, marked as answer]
This is now possible in >=24.2 via the `COCKROACH_ARGS` environment variable.

```yaml
services:
  cockroach:
    image: cockroachdb/cockroach
    env:
      COCKROACH_ARGS: "start-single-node --insecure"
    options: >-
      --health-cmd "curl -f http://localhost:8080/health?ready=1"
```
