### ISSUE TITLE
TestCCLLogic_multi_region is flaky (modifying the regions of system database)

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#100404]
The test added in https://github.com/cockroachdb/cockroach/pull/98554 is flaky.

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9369070?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
        expected:
        modifying the regions of system database is not supported
        got:
        pq: user testuser may not modify the system database
```
