### ISSUE TITLE
Acceptance Testing: Datadog HTTP Log Export API is missing fields/tags

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/cockroach#106405]
The logs collected in Datadog using the new [Datadog HTTP Log Export API](https://docs.datadoghq.com/api/latest/logs/) for Self-Hosted are missing critical fields and tags to help users identify, filter, build, and correlate dashboards. 

This issue tracks 

1. Providing a default/static fields and tags for critical fields:

- SOURCE: cockroachdb
- HOST: hostname of the node

2. Allow generic/custom tagging during CRDB deployment in the YAML file, example tags and values:
```yaml
tags:
   env: <prod, or production, or pmt-prod>
   service: <pmt-database, or cockroach, or app-name>
   team: <payments>
   chargeback: <ops-estore>
   apps: <store>
```

Custom tagging will override any default fields (SOURCE and HOST).
 

[Agent log (with expected tags/fields)
](https://app.datadoghq.com/logs?query=&cols=host%2Cservice&event=AgAAAYkxB1BOKP8_ywAAAAAAAAAYAAAAAEFZa3hCMXZyQUFBSUwyZFhoNXlnWGdBQgAAACQAAAAAMDE4OTMxMDctNjdkMC00ZjQ4LThiYzAtODY2NWM4ZmU1OTg3&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1688740079295&to_ts=1688743679295&live=true)

[HTTP Export API log
](https://app.datadoghq.com/logs?query=-source%3Acockroachdb&cols=host%2Cservice&event=AgAAAYkHS0qGipwH9QAAAAAAAAAYAAAAAEFZa0hTMHFHQUFDRllmY2liaDlQN0FBQQAAACQAAAAAMDE4OTA3ZDUtM2UzOS00NGRjLWE2NWEtN2E2MGY3YzIyNjQ0&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1686151005157&to_ts=1688743005157&live=true)

Related issue:

- https://github.com/cockroachdb/cockroach/issues/103477

Jira issue: CRDB-29555

Epic CRDB-32142

**Comment by levihernandez** [comment]
Tag structure can work in the following form:
* Send tags automatically by the CRDB binary:
  * HOST
  * SOURCE: cockroachdb
  * CLUSTER ID
  * NODE ID
  * REGION
  * VERSION (RELEASE)
  
* Allow tag customization during CRDB deployment in a YAML (`env`, and `service` are mandatory tags that the user needs to customize), example tags and values:
```yaml
tags:
  - env: <prod, or production, or pmt-prod>
  - service: <pmt-database, or cockroach, or app-name>
  - team: <payments>
  - chargeback: <ops-estore>
  - apps: <store>
```

**Comment by kevin-v-ngo** [comment]
@levihernandez we have a few fields already in the log😀 Going to update the issue

"attributes": {
			"tenant_id": 1,
			"severity": "INFO",
			"line": 32,
			"channel": "TELEMETRY",
			"severity_numeric": 1,
			"version": "v23.1.5",
			"channel_numeric": 12,
			"tags": {
				"hostnossl": "",
				"client": "10.142.1.78:48852",
				"user": "root",
				"n": "3"
			}
"tags": {
				"hostnossl": "",
				"client": "10.142.1.78:48852",
				"user": "root",
				"n": "3"
			},

**Comment by dhartunian** [comment]
@kevin-v-ngo this feature could be implemented as a static set of tags that are appended to logs on arbitrary sinks. I assume all of the required tags are static per node. I do worry a bit about how far we're going to implement features that are typically the responsibility of external observability agents. Do we know where we're going to draw the line? What if a customer wants to have different tags on different logging channels?

Also, I assume in your example you would want the following instead of a separate object per tag:
```yaml
tags:
  env: <prod, or production, or pmt-prod>
  service: <pmt-database, or cockroach, or app-name>
  team: <payments>
  chargeback: <ops-estore>
  apps: <store>
```
