### ISSUE TITLE
Setting up single node container with vscode devcontainers doesn't work

### ISSUE THREAD

**Issue by raokrutarth** [cockroachdb/cockroach#107416]
**Describe the problem**

Got pretty frustrated trying to setup cockroachdb for my teams dev env for people to try it out. 

We have postgres containers that work flawlessly and I thought the dev env would be a nice place to try out CDB. The container does not honor the env vars COCKROACH_USER, COCKROACH_DATABASE and COCKROACH_PASSWORD. I have read through https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac but no idea why the sql connection url keeps defaulting to root.

**To Reproduce**

Create cert files and save those in local dirs:

```bash
docker run -it --rm -v $PWD/.devcontainer/dev-db-auth:/etc/certs cockroachdb/cockroach:v23.1.5 cert create-ca --certs-dir=/etc/certs/certs-public --ca-key=/etc/certs/cert-keys

docker run -it --rm -v $PWD/.devcontainer/dev-db-auth:/etc/certs cockroachdb/cockroach:v23.1.5 cert create-node db-dev --certs-dir=/etc/certs/certs-public --ca-key=/etc/certs/cert-keys
```

Update the yaml in docker-compose.yaml that resides in .devcontainer/:

```yaml
...
 db:
    hostname: db-dev
    container_name: cashflow-db
    image: cockroachdb/cockroach:v23.1.5
    command:
      - start-single-node
      - --sql-addr=:5432
      - --accept-sql-without-tls
      - --certs-dir=/etc/dev-certs
    volumes:
      - ./dev-db-auth/certs-public:/etc/dev-certs
    environment:
      - COCKROACH_USER: dev
      - COCKROACH_DATABASE: cashflow
      - COCKROACH_PASSWORD: djZMi4hGgSLpbc1B
...
```

Restart the container:
```bash
 dc -f ./.devcontainer/docker-compose.yml -p monorepo_devcontainer up db --force-recreate
```

Resulting logs and connection strings:

```text
db  | *
db  | * WARNING: advertise address "127.0.0.1" not in node certificate (IP=; DNS=db-dev; CN=node)
db  | * advertise SQL address "127.0.0.1" not in node certificate (IP=; DNS=db-dev; CN=node)
db  | * Secure client connections are likely to fail.
db  | * Consider extending the node certificate or tweak --listen-addr/--advertise-addr/--sql-addr/--advertise-sql-addr.
db  | *
db  | CockroachDB node starting at 2023-07-22 10:30:37.791360184 +0000 UTC m=+6.817919430 (took 6.5s)
db  | build:               CCL v23.1.5 @ 2023/07/01 01:33:00 (go1.19.10)
db  | webui:               https://127.0.0.1:8080
db  | sql:                 postgresql://root@127.0.0.1:5432/defaultdb?sslmode=verify-full&sslrootcert=%2Fetc%2Fdev-certs%2Fca.crt
db  | sql (JDBC):          jdbc:postgresql://127.0.0.1:5432/defaultdb?sslmode=verify-full&sslrootcert=%2Fetc%2Fdev-certs%2Fca.crt&user=root
db  | RPC client flags:    /cockroach/cockroach <client cmd> --host=127.0.0.1:26257 --certs-dir=/etc/dev-certs
db  | logs:                /cockroach/cockroach-data/logs
db  | temp dir:            /cockroach/cockroach-data/cockroach-temp472145336
db  | external I/O path:   /cockroach/cockroach-data/extern
db  | store[0]:            path=/cockroach/cockroach-data
db  | storage engine:      pebble
db  | clusterID:           99812967-31d8-4bbb-984d-d22a4e975869
db  | status:              restarted pre-existing node
db  | nodeID:              1
```

**Expected behavior**
The sql url should reflect the env vars set in the container

**Additional data / screenshots**
N/A

Jira issue: CRDB-30030

**Comment by ZhouXing19** [comment]
@raokrutarth Thanks for bringing up this issue. You're right, it would be beneficial to display a SQL URL that reflects the customized db/user.

For now, you can manually modify the default username and database name in the URL to this:
```
postgresql://dev:djZMi4hGgSLpbc1B@127.0.0.1:5432/cashflow?sslmode=verify-full&sslrootcert=%2Fetc%2Fdev-certs%2Fca.crt
```

Additionally, if you don't use the --insecure flag when running start-single-node, a certificate directory will be created automatically (default path `/cockroach/certs` in the container). You can start a single node cluster using this command:
```sh
docker run -d \
    -e COCKROACH_DATABASE=mydb \
    -e COCKROACH_USER=myuser \
    -e COCKROACH_PASSWORD=12345 \
    --name=roach1 \
    --hostname=roach1 \
    -p 26257:26257 -p 8080:8080 \
    cockroachdb/cockroach:latest start-single-node
```

And to connect to the SQL console:

```
docker exec -it roach1 ./cockroach sql --url="postgresql://myuser:12345@127.0.0.1:26257/defaultdb?sslcert=certs%2Fclient.myuser.crt&sslkey=certs%2Fclient.myuser.key&sslmode=verify-full&sslrootcert=certs%2Fca.crt"
```

Hope it helps! Please let us know if this doesn't work or if you have other questions.

**Comment by rafiss** [comment]
@raokrutarth To explain a bit more, the URL that you are seeing is the one that is always logged during startup of any CockroachDB node. It's not something that comes from the special docker container logic.

**Comment by raokrutarth** [comment]
Thanks for the help! this is working. Agreed, the startup log message is a little misleading.

```yaml
...
# docker-compose.yml
  dbc:
    hostname: dbc-dev
    container_name: gops-dev-dbc
    image: cockroachdb/cockroach:v23.1.5
    command:
      - start-single-node
      - --sql-addr=:5432
      - --accept-sql-without-tls
      - --certs-dir=/etc/dev-certs
    volumes:
      - ./dev-db-auth/certs-public:/etc/dev-certs
    environment:
      - COCKROACH_USER=dev
      - COCKROACH_DATABASE=playspace_db
      - COCKROACH_PASSWORD=djZMi4hGgSLpbc1B
    ports:
      - "35432:5432"
 ...
```

Followed by:
 
```bash
psql 'postgresql://dev:djZMi4hGgSLpbc1B@127.0.0.1:35432/playspace_db?sslmode=disable'
```
