### ISSUE TITLE
CockroachDB Grafana Dashboards not showing any metrics

### ISSUE THREAD

**Issue by mprimeaux** [cockroachdb/cockroach#110778]
**Describe the problem**

The Grafana dashboards for CockrochDB aren’t displaying metrics.

**To Reproduce**

I am using version [`11.1.7` of the Helm chart](https://github.com/cockroachdb/helm-charts/blob/03e13d1fb355515273da82e2f1062b9f1368befd/cockroachdb/Chart.yaml#L5). When I enable the prometheus service monitor, it does indeed create the service monitor with the following scrape endpoint:

```yaml
Spec:
  Endpoints:
    Interval:  10s
    Path:      /_status/vars
    Port:      http
```

I port forward on `8080` to one of the nodes but curl returns a HTTP redirect. 

```shell
curl http://localhost:8080/_status/vars
<a href="https://localhost:8080/_status/vars">Temporary Redirect</a>.
```

No big deal since Prometheus should follow the redirect. However, the HTTPS call fails using curl with the following:

```shell
curl https://localhost:8080/_status/vars
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

This is due to the default values in the the CockroachDB chart being set to use the the self-signer for the related X.509 certs. I then changed my curl command to the following:

```shell
curl https://localhost:8080/_status/vars --insecure

rebalancing_replicas_queriespersecond_bucket{store="3",node_id="3",le="1"} 31544
rebalancing_replicas_queriespersecond_bucket{store="3",node_id="3",le="1.664445"} 31630
rebalancing_replicas_queriespersecond_bucket{store="3",node_id="3",le="2.770377"} 31727
rebalancing_replicas_queriespersecond_bucket{store="3",node_id="3",le="4.611141"} 31813
rebalancing_replicas_queriespersecond_bucket{store="3",node_id="3",le="7.674991"} 32261
...
```

The `--insecure` option now allows the command to return metrics.  I then decided to explicitly configure a static Prometheus scrape job. Here is that stanza for the `kube-prometheus-stack` Helm chart:

```yaml
   - job_name: "cockroach-db-1"
        metrics_path: /_status/vars
        scrape_interval: 10s
        static_configs:
          - targets: [ core-db-1-cockroachdb-public.go-scriptures.svc:8080 ]
        scheme: https
        tls_config:
          insecure_skip_verify: true
````

The Prometheus Overview dashboards show metrics being successfully scraped along with no scrape failures. This is SS-01, below.

These are the [CockroachDB dashboards](https://github.com/cockroachdb/cockroach/tree/master/monitoring/grafana-dashboards/by-cluster) that I directly imported into Grafana.

**Expected behavior**

The expectation is for the CockroachDB dashboards to display the related metrics.

**Additional data / screenshots**

Here are a few screenshots for context.

**SS-01:** The Prometheus scrape jobs. The job named `serviceMonitor/go-scriptures/core-db-1-cockroachdb/0` is the scrape of the service monitor created by CockroachDB. The job named `cockroach-db-1` is the static scrape job I created using the above stanza.

<img width="1263" alt="SS-01" src="https://github.com/cockroachdb/cockroach/assets/293512/77d9d5c1-ddc0-45f1-9494-f06aa8be9cc5">

**SS-02:** The CRDB Console: Overview with no metrics being shown.

<img width="1726" alt="SS-02" src="https://github.com/cockroachdb/cockroach/assets/293512/0e552f8a-a27c-4f13-b53f-fa3b34ee2874">

**SS-03:** The CRDB Console: Runtime with no cluster in the dropdown.

<img width="2073" alt="SS-03" src="https://github.com/cockroachdb/cockroach/assets/293512/3867e768-90e2-4510-9a0f-a1a083d1693b">

I suspected no metrics were making their way into Prometheus. To support this hypothesis, I searched for `kv_replica` on the "Explore" page in Grafana but was wrong. Metrics are indeed being received via the static scrape config I defined.

<img width="1278" alt="SS-04" src="https://github.com/cockroachdb/cockroach/assets/293512/516468e6-3318-4af3-b6d1-137a8cb30fea">

However, even so, the CockroachDB dashboards aren't showing metrics.

**Environment:**
 - CockroachDB 23.1.10
 - OS:  Minikube (latest version) on macOS
 - Kubernetes 1.27.4
 - CPU Architecture: ARM64

**Additional context**
The impact is we are unable to observe CockroachDB and therefore unable to set alert thresholds. We are trying to move our workload into production so any help is greatly appreciated. 

When the intrinsic CockroachDB Service Monitor is enabled, the error I see in the CockroachDB logs on each pod is:

```shell
db E230917 00:04:48.600822 327175 (gostd) net/http/server.go:3228 ⋮ [-] 9584  ‹http: TLS handshake error from 10.244.0.91:39796: remote error: tls: bad certificate›
```

The `10.244.0.91` address is the Prometheus pod that's attempting to scrape the CockroachDB pod. 

I'll continue to debug on my end but do appreciate any guidance.

Jira issue: CRDB-31607

**Comment by mprimeaux** [comment]
As an update, there is more detail to this issue in [cockroachdb/docs#6320](https://github.com/cockroachdb/docs/issues/6320#issuecomment-1728515219).

**Comment by abarganier** [comment]
Hi @mprimeaux - apologies for the inconvenience here. Let's see if we can get this sorted out!

For starters, I noticed that you said:
> To support this hypothesis, I searched for kv_replica on the "Explore" page in Grafana but was wrong. Metrics are indeed being received via the static scrape config I defined.

Can you confirm whether you're able to view CockroachDB metrics in Grafana using the "Explore" page (the one where you can write free-form queries)? 

You mentioned:
> Metrics are indeed being received via the static scrape config I defined.

I'd just like to confirm that the metrics are being successfully scraped by Prometheus before we dig deeper. If the metrics are successfully being scraped by Prometheus, then my suspicion is with the dashboard configs themselves. 

Thanks for confirming these basics.

**Comment by mprimeaux** [comment]
Hi @abarganier. Sorry for the ambiguity with the metric. Yes, I do see CockroachDB metrics. I chose a metric as a result of the following command against one of the CockroachDB nodes.

```shell
curl https://localhost:8080/_status/vars --insecure
```

<img width="1274" alt="SS-01" src="https://github.com/cockroachdb/cockroach/assets/293512/afaaf456-7164-4c0a-90c0-34f248c0bd9b">

Here are those metrics in Grafana.

<img width="643" alt="SS-02" src="https://github.com/cockroachdb/cockroach/assets/293512/fee9b24c-a20a-4cd7-829f-8d23018b3d0f">

**Comment by abarganier** [comment]
@mprimeaux Thank you for confirming! If the metrics are making it into the TSDB, then something must be up with the dashboard config 🤔 

I will dig into this a bit and let you know what I find.

**Comment by mprimeaux** [comment]
So, the issue was in the job name of the related dashboard. Here's an excerpt:

```yaml
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${DS_PROMETHEUS}"
          },
          "exemplar": true,
          "expr": "sum(rate(sql_update_count{job=\"cockroachdb\",cluster=~\"$cluster\",instance=~\"$node\"}[$__rate_interval]))",
          "interval": "",
          "legendFormat": "Updates",
          "refId": "B"
        },
```

Note the `job=\"cockroachdb\"` line. I guess this the release name given in the `helm install` command.   My release is named `core-db-1-cockroachdb`. I performed a find and replace in the JSON of the dashboard.

**Comment by abarganier** [comment]
@mprimeaux Nice catch, apologies for the confusion here. It seems like these dashboards make assumptions about the available labelset on the metrics. 

Let me do some digging and see what the original intention was with these labels... IIRC, we have a docker-compose meant to demo some Grafana dashboards ([link](https://github.com/cockroachdb/cockroach/tree/master/monitoring/demo)) - these might have been built against that, which may have been where the incorrect assumption regarding the presence of the `job` label came from.

**Comment by mprimeaux** [comment]
No worries, @abarganier.  

The primary issue I ran into is **detailed** [here](https://github.com/cockroachdb/docs/issues/6320#issuecomment-1728515219) with a **summary** [above](https://github.com/cockroachdb/cockroach/issues/110778#issuecomment-1730357383).  I plan to submit a PR to address this scenario unless it's already in progress in another PR.

The secondary "issue" was with the job name in the Grafana dashboard.  The workaround is a find and replace so not a big deal but it would be helpful if the job name was perhaps added as a variable. I'm happy to help with that, also.

Let me know your thoughts when you're above water again.

**Comment by abarganier** [comment]
@mprimeaux I believe this is due to some confusion around who the intended user is for these dashboards.

We have internal test infrastructure that uses a copy of these dashboards in a Prometheus/Grafana setup used to monitor the tests (e.g. a copy of these dashboards was pulled into this directory: https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/roachprod/grafana).

I believe the test infra assumes the `job="cockroachdb"` label, which is where I think this is coming from.

I've talked with our test engineering team (cc @smg260) about this. We believe that lifting these dashboards into their own repo would help us better document & manage them, which they have agreed to take ownership of. 

@smg260 let me know if I can do anything on my end to help with the process. I think we might want to consider moving the demo docker-compose as well.

**Comment by mprimeaux** [comment]
@abarganier Thanks much for the detail here; very helpful to me. Shall I close this issue?

**Comment by mprimeaux** [comment]
@abarganier I was thinking through another possible option since the dashboards are very useful. You could consider keeping the dashboards with the CockroachDB Helm chart and deploying them each as a `ConfigMap` with the appropriate templating support to populate the correct job name. 

For example, assuming the json files were placed in a `dashboards` subfolder that is peer to the [`templates`](https://github.com/cockroachdb/helm-charts/tree/master/cockroachdb/templates) folder over in the `helm-charts` repository, you could add a file in the `templates` folder named `configmap-grafana-dashboards.yaml` containing the dashboards:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: cockroachdb-overview-dashboard-{{ .Release.Namespace }}-configmap
data:
  overview.json: |-
{{ .Files.Get "dashboards/overview.json" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: cockroachdb-distributed-dashboard-{{ .Release.Namespace }}-configmap
data:
  overview.json: |-
{{ .Files.Get "dashboards/distributed.json" | indent 4 }}
```

...etc. Just a thought.
