### ISSUE TITLE
cgroups: systemd cgroup missing CPU limit interface file

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#111648]
**Describe the problem**

Details in https://forum.cockroachlabs.com/t/unable-to-get-cpu-capacity/6022.

Following our [Deploy CockroachDB On-premises](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises?%20filters=systemd) doc, we've had a user encounter missing `cpu.max` files in the cgroup subsystem. All other non-root CPU interface files are also missing in this case.

CRDB should fall back to system CPU limits, but the logs are flooded with `unable to get CPU capacity: error when read cpu quota from cgroup v2`.

**Environment:**
 - CockroachDB version 23.1.6
 - Server OS: Ubuntu 22.04

Jira issue: CRDB-32004

gz#20190

**Comment by mmack** [comment]
Same here:

Version: **CockroachDB CCL v23.1.14**

``` 
cockroachdb-0 db I240123 15:37:07.367201 1 server/status/recorder.go:752 ⋮ [n?] 3  ‹available memory from cgroups (0 B) is unsupported, using system memory 63 GiB instead: no cgroup memory controller detected›
cockroachdb-0 db I240123 15:37:07.367253 1 1@cli/start.go:589 ⋮ [n?] 4  soft memory limit of Go runtime is set to 35 GiB
cockroachdb-0 db I240123 15:37:07.380229 1 server/status/recorder.go:752 ⋮ [T1,n?] 5  ‹available memory from cgroups (0 B) is unsupported, using system memory 63 GiB instead: no cgroup memory controller detected›
cockroachdb-0 db I240123 15:37:07.380337 1 server/config.go:661 ⋮ [T1,n?] 6  system total memory: 63 GiB
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7  server configuration:
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹max offset             500000000›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹cache size             16 GiB›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹SQL memory pool size   16 GiB›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹scan interval          10m0s›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹scan min idle time     10ms›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹scan max idle time     1s›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹event log enabled      true›
cockroachdb-0 db I240123 15:37:07.380370 1 server/config.go:663 ⋮ [T1,n?] 7 +‹span configs enabled   true›

``` 

OS:

```
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
```

Resources on K8s:
```
    resources:                                                                                                                                                                                                      
      limits:                                                                                                                                                                                                       
        cpu: "4"                                                                                                                                                                                                    
        memory: 16Gi                                                                                                                                                                                                
      requests:                                                                                                                                                                                                     
        cpu: 100m                                                                                                                                                                                                   
        memory: 2Gi   
```
