### ISSUE TITLE
Degraded performance in CPU, RAM and disk utilisation

### ISSUE THREAD

**Issue by VitoCrl** [cockroachdb/cockroach#118752]
**Describe the problem**

We have a VPS with currently 4 cores and 8GB RAM on which 11 different Netbird installations are running self-hosted. One Netbird installation consists of Zitadel + Cockroachdb + Netbird. We have started to notice a high utilisation of both RAM and CPU, but especially writing to disk despite the fact that all dockers are configured to log only info and not debug.

**To Reproduce**

Install a version of Netbird (self-hosted): 
`export NETBIRD_DOMAIN=netbird.example.com; curl -fsSL https://github.com/netbirdio/netbird/releases/latest/download/getting-started-with-zitadel.sh | bash` it will deploy the same enviroment in a lower scale.

**Expected behavior**
A much lower consumption of resources, and it is also not very clear to me why all these cockroach threads are opened for a single container on which it is running

**Additional data / screenshots**
![image](https://github.com/cockroachdb/cockroach/assets/45329342/e4744202-1d96-42db-9982-3bae6af81f73)
![image](https://github.com/cockroachdb/cockroach/assets/45329342/4d23d2d1-ec87-4e51-9ca6-273ac32b97e9)
![image](https://github.com/cockroachdb/cockroach/assets/45329342/371809e4-1d52-4da2-a200-214da6a895e4)
![image](https://github.com/cockroachdb/cockroach/assets/45329342/ab3d0fe6-0fda-4a9b-b589-cc3bf537ba0e)
![image](https://github.com/cockroachdb/cockroach/assets/45329342/7d94f124-5f24-49ea-bdaf-194b7a1d0942)

**Environment:**
 - CockroachDB version 22.2.2 
 - Zitadel version 2.31.3
 - Server OS: Debian 12
 - Client app cockroach sql

**Comment by arulajmani** [comment]
From the screenshot, it looks like there's quite a few `cockroach start single-node` commands that are being run. Each of those commands runs one instance of a single node cluster. 

I'm not familiar with Netbird, but if you say that's what's creating the clusters, maybe that's the best place to start looking instead.

**Comment by VitoCrl** [comment]
Hi @arulajmani thank you very much for your reply, I don't know if it would help you or anyone else who wants to contribute this is the file that is executed to deploy the instances: [getting-started-with-zitadel.sh](https://github.com/netbirdio/netbird/blob/main/infrastructure_files/getting-started-with-zitadel.sh)

Eventually the docker-compose.yml is generated with this crdb service
```
 # CockroachDB for zitadel
    crdb53eaf49f-d54c-4ad5-8751-021914c72033:
        restart: 'always'
        networks: [netbird].
        image: 'cockroachdb/cockroach:v22.2.2'
        command: 'start-single-node --advertise-addr crdb53eaf49f-d54c-4ad5-8751-021914c72033'
        volumes:
            - netbird_crdb53eaf49f-d54c-4ad5-8751-021914c72033_data:/cockroach/cockroach-data
            - netbird_crdb53eaf49f-d54c-4ad5-8751-021914c72033_certs:/cockroach/certs
            - netbird_zitadel53eaf49f-d54c-4ad5-8751-021914c72033_certs:/zitadel-certs
        healthcheck:
            test: [ 'CMD', 'curl', '-f', 'http://localhost:8080/health?ready=1' ]
            interval: '10s'
            timeout: '30s'
            retries: 5
            start_period: '20s'
```

**Comment by VitoCrl** [comment]
Hi guys, would anyone be able to provide support?

**Comment by mlsmaycon** [comment]
Hello @arulajmani, Maycon from NetBird here, the processes that you saw in the screenshot is from a single docker container running in single-node mode. Below you will find the the docker-compose service:

```yaml
  crdb:
    restart: 'always'
    networks: [netbird]
    image: 'cockroachdb/cockroach:v22.2.2'
    command: 'start-single-node --advertise-addr crdb'
    volumes:
      - netbird_crdb_data:/cockroach/cockroach-data
      - netbird_crdb_certs:/cockroach/certs
      - netbird_zitadel_certs:/zitadel-certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health?ready=1" ]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
```

Besides that, the main process that utilizes the database is Zitadel, an identity provider. Before going back to them, I want to understand if you see an issue with:
1. the queries and stats shared in the other screenshots above
2. what do you think about the health check configuration for this container, could it be a problem?
3. We are using TLS connections. Perhaps that could be an issue here, too.
