### ISSUE TITLE
Cockroach CLI commands fail when using a docker cluster because of max_read_buffer_message_size

### ISSUE THREAD

**Issue by SCedricThomas** [cockroachdb/cockroach#122355]
**Describe the problem**

I am encountering the following error logs on some commands when a cluster is deployed using the docker image:
```
cockroachdb-roach1-1   | E240405 07:53:14.799470 3199 1@server/server_sql.go:1774 ⋮ [T1,n1,client=‹10.0.0.5:59610›] 129  serving SQL client conn: message size ‹352 MiB› bigger than maximum allowed message size ‹16 MiB›
cockroachdb-roach1-1   | E240405 07:53:14.799470 3199 1@server/server_sql.go:1774 ⋮ [T1,n1,client=‹10.0.0.5:59610›] 129 +HINT: ‹the maximum message size can be configured using the sql.conn.max_read_buffer_message_size cluster setting›
```

The commands impacted so far are:
- cockroach gen haproxy
- cockroach node drain

These commands work when I'm not using docker.

**To Reproduce**

I've set up a secure cluster using docker compose and it seems that some commands aren't working.
Here is the docker-compose.yml I am using:

<details>
<summary>docker-compose.yml</summary>

```
version: '3'
services:
  roach1:
    image: cockroachdb/cockroach:v23.1.17
    hostname: roach1
    volumes:
      - ./_dev/roach1/data:/cockroach/cockroach-data
      - ./_dev/roach1/certs:/cockroach/certs
    ports:
      - "8081:8080"
    networks:
      roachnet:
        ipv4_address: 10.0.0.2
    command: start --logtostderr --certs-dir=certs --join=roach1:26357,roach2:26357,roach3:26357 --advertise-addr=roach1:26357 --http-addr=roach1:8080 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --cache=.25 --max-sql-memory=.25
  roach2:
    image: cockroachdb/cockroach:v23.1.17
    hostname: roach2
    volumes:
      - ./_dev/roach2/data:/cockroach/cockroach-data
      - ./_dev/roach2/certs:/cockroach/certs
    ports:
      - "8082:8080"
    networks:
      roachnet:
        ipv4_address: 10.0.0.3
    command: start --logtostderr --certs-dir=certs --join=roach1:26357,roach2:26357,roach3:26357 --advertise-addr=roach2:26357 --http-addr=roach2:8080 --listen-addr=roach2:26357 --sql-addr=roach2:26257 --cache=.25 --max-sql-memory=.25
  roach3:
    image: cockroachdb/cockroach:v23.1.17
    hostname: roach3
    volumes:
      - ./_dev/roach3/data:/cockroach/cockroach-data
      - ./_dev/roach3/certs:/cockroach/certs
    ports:
      - "8083:8080"
    networks:
      roachnet:
        ipv4_address: 10.0.0.4
    command: start --logtostderr --certs-dir=certs --join=roach1:26357,roach2:26357,roach3:26357 --advertise-addr=roach3:26357 --http-addr=roach3:8080 --listen-addr=roach3:26357 --sql-addr=roach3:26257 --cache=.25 --max-sql-memory=.25
  client:
    image: cockroachdb/cockroach:v23.1.17
    hostname: client
    volumes:
      - ./_dev/client/certs:/cockroach/certs
    networks:
      roachnet:
        ipv4_address: 10.0.0.5

networks:
  roachnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
```

</details>

Here are the steps I followed to setup my cluster:

1. Generate the folders and the certificates used by the cluster with a script:

<details>
<summary>script.sh</summary>

```
#!/bin/bash

# Create the directories for the certificates and data
mkdir -p ./_dev/certs

mkdir -p ./_dev/roach1/data
mkdir -p ./_dev/roach1/certs

mkdir -p ./_dev/roach2/data
mkdir -p ./_dev/roach2/certs

mkdir -p ./_dev/roach3/data
mkdir -p ./_dev/roach3/certs

mkdir -p ./_dev/client/certs


cockroach="docker compose run --rm -v $(pwd)/_dev:/cockroach/_dev client"

# Generate the CA key and certificate for the cluster
$cockroach cert create-ca \
--certs-dir=./_dev/certs \
--ca-key=./_dev/ca.key

# Generate the key and certificate for each node
# Then move them in the appropriate directories

# Roach1
$cockroach cert create-node \
10.0.0.2 \
10.0.0.2 \
roach1  \
localhost \
127.0.0.1 \
10.0.0.10 \
loadbalancer  \
--certs-dir=./_dev/certs \
--ca-key=./_dev/ca.key
cp ./_dev/certs/ca.crt ./_dev/roach1/certs
mv ./_dev/certs/node.crt ./_dev/roach1/certs
mv ./_dev/certs/node.key ./_dev/roach1/certs

# Roach2
$cockroach cert create-node \
10.0.0.3 \
10.0.0.3 \
roach2  \
localhost \
127.0.0.1 \
10.0.0.10 \
loadbalancer  \
--certs-dir=./_dev/certs \
--ca-key=./_dev/ca.key
cp ./_dev/certs/ca.crt ./_dev/roach2/certs
mv ./_dev/certs/node.crt ./_dev/roach2/certs
mv ./_dev/certs/node.key ./_dev/roach2/certs

# Roach3
$cockroach cert create-node \
10.0.0.4 \
10.0.0.4 \
roach3  \
localhost \
127.0.0.1 \
10.0.0.10 \
loadbalancer  \
--certs-dir=./_dev/certs \
--ca-key=./_dev/ca.key
cp ./_dev/certs/ca.crt ./_dev/roach3/certs
mv ./_dev/certs/node.crt ./_dev/roach3/certs
mv ./_dev/certs/node.key ./_dev/roach3/certs

# Generate the key and certificate for the client
# Then move them in the appropriate directories
$cockroach cert create-client \
root \
--certs-dir=./_dev/certs \
--ca-key=./_dev/ca.key
cp ./_dev/certs/ca.crt ./_dev/client/certs
mv ./_dev/certs/client.root.crt ./_dev/client/certs
mv ./_dev/certs/client.root.key ./_dev/client/certs
```

</details>

2. Start the cluster
```
docker compose up -d roach1 roach2 roach3
```

3. Init the cluster
```
docker compose run --rm client --certs-dir=certs --host=roach1:26357 init
```

4. Try to generate an HAProxy config through the client container
```
docker compose run --rm --entrypoint=/bin/bash client
cockroach gen haproxy --certs-dir=./certs --host=10.0.0.2:26257
```

**Expected behavior**

The HAProxy config should be generated without any issue.

**Environment:**
 - CockroachDB: v23.1.17
 - Server OS: Ubuntu 22.04 
 - Docker Server: 26.0.0
 - Docker Client: 26.0.0
 - docker-compose: v2.10.2

**Additional context**

I tried to fix the issue by setting the `sql.conn.max_read_buffer_message_size` cluster setting to 500 MiB with the following query:
```sql
SET CLUSTER SETTING sql.conn.max_read_buffer_message_size = "500 MiB";
```

However, after rebooting the cluster with the updated settings, I am now encountering the following error:
```
E240403 11:53:22.760265 3305 1@server/server_sql.go:1774 ⋮ [T1,n1,client=‹10.0.0.5:59538›] 177  serving SQL client conn: ‹unexpected EOF›
```

My guts feeling is that it is in fact not related to max_read_buffer_message_size

This issue hasn't been encountered by using a cluster using the binary release directly:
```bash
cockroach start --store="$(realpath cockroach-1/data)" --certs-dir=cockroach-1/certs --advertise-addr=localhost:8090 --http-addr=0.0.0.0:8085 --listen-addr=0.0.0.0:8090 --join=localhost:8090,localhost:8091,localhost:8092 --cache=.25 --max-sql-memory=.25 --background
cockroach start --store="$(realpath cockroach-2/data)" --certs-dir=cockroach-2/certs --advertise-addr=localhost:8091 --http-addr=0.0.0.0:8086 --listen-addr=0.0.0.0:8091 --join=localhost:8090,localhost:8091,localhost:8092 --cache=.25 --max-sql-memory=.25 --background
cockroach start --store="$(realpath cockroach-3/data)" --certs-dir=cockroach-3/certs --advertise-addr=localhost:8092 --http-addr=0.0.0.0:8087 --listen-addr=0.0.0.0:8092 --join=localhost:8090,localhost:8091,localhost:8092 --cache=.25 --max-sql-memory=.25 --background
``` 

Jira issue: CRDB-37828
