### ISSUE TITLE
`UNION` with `ORDER BY` and `LIMIT` produced wrong result in multi-node version but not in single-node version (1)

### ISSUE THREAD

**Issue by r33s3n6** [cockroachdb/cockroach#122960]
**Describe the problem**
`UNION` with `ORDER BY` and `LIMIT` produced wrong result in multi-node version but not in single-node version

**To Reproduce**
First execute `init.sql` to create the table. Then executing `error.sql` yields unexpected results. Note that reproducing these results might not be entirely stable. Typically, it can be completed within three attempts. You can try executing multiple times or execute it again after rebuilding the table.
[init.sql.txt](https://github.com/cockroachdb/cockroach/files/15090483/init.sql.txt)
[error.sql.txt](https://github.com/cockroachdb/cockroach/files/15090481/error.sql.txt)

**Expected behavior**
The multi-node version of CockroachDB produced incorrect results. The correct result should have only been one line, but it outputted 48 lines instead.
[output_re_main.log](https://github.com/cockroachdb/cockroach/files/15090484/output_re_main.log)
[output_re_single.log](https://github.com/cockroachdb/cockroach/files/15090485/output_re_single.log)

**Environment:**
 - CockroachDB version: 23.1.9
 - Server OS: `Linux a002 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - Client app: postgresql odbc/psql

docker compose file:
```
version: '3.5'

services:
  crdb1:
    image: cockroachdb/cockroach:v23.1.19
    command: "start --advertise-addr=crdb1:26357 --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb1_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.11

  crdb2:
    image: cockroachdb/cockroach:v23.1.19
    command: "start --advertise-addr=crdb2:26357 --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb2_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.12

  crdb3:
    image: cockroachdb/cockroach:v23.1.19
    command: "start --advertise-addr=crdb3:26357 --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb3_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.13

  crdb_single:
    image: "cockroachdb/cockroach:v23.1.19"

    command: start-single-node --insecure
    volumes:
      - "crdb_single_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.21

volumes:
  crdb1_data:
  crdb2_data:
  crdb3_data:
  crdb_single_data:


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24
          gateway: 10.0.5.254
```

#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned possible vulnerabilities that may lead to database logic error.

**Comment by r33s3n6** [comment]
I apologize for accidentally mixing up the attachments for the SQL output results of these two issues(#112960 and #112961 ). I have now edited and corrected them. I'm very sorry for the confusion.

**Comment by michae2** [comment]
Thank you for filing the error report @r33s3n6! Using your corrected files, I have successfully reproduced on a 3-node roachprod cluster running the tip of master (379d332c9a4ce49cda4a3565a852e7ddb850ffb5).

**Comment by mgartner** [comment]
Now that we have a repro, let's figure out how to prioritize fixing it.

**Comment by r33s3n6** [comment]
We found a stable reproduction method:
```sql

CREATE TABLE t1 as 
  SELECT null::int4 as c1, null::int4 as c2 WHERE false;
ALTER TABLE t1 configure ZONE 
  USING constraints = '[+region=r1]';

INSERT into t1 (c1, c2) VALUES (1, 1);
CREATE INDEX idx1 on t1 (c2);


CREATE TABLE t2 (c1 int4 PRIMARY KEY, c2 bool);
ALTER TABLE t2 configure ZONE 
  USING constraints = '[+region=r3]';

INSERT into t2 (c1, c2) VALUES 
  (1, null), (2, null), (3, null), (4, null);

-- ATTENTION: you should wait some time here before executing the following statement
SELECT false as c0 FROM t1
  WHERE (SELECT 1) is NULL
UNION ALL
  (SELECT DISTINCT EXISTS (SELECT 1 WHERE false)
  FROM t2)
ORDER BY c0 LIMIT 2;
```

deploy:
```bash
export CR_SUBNET=10.5.6
export CR_IMAGE="cockroachdb/cockroach:v23.1.19"

docker compose up -d
```

```yaml
x-service-defaults: &service_defaults
  image: ${CR_IMAGE:?please provide the image name}

services:
  crdb1:
    <<: *service_defaults
    command: "start --advertise-addr=crdb1:26357 --locality=region=r1,zone=r1a --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb1_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.11

  crdb2:
    <<: *service_defaults
    command: "start --advertise-addr=crdb2:26357 --locality=region=r2,zone=r2a --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb2_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.12

  crdb3:
    <<: *service_defaults
    command: "start --advertise-addr=crdb3:26357 --locality=region=r3,zone=r3a --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb3_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.13

volumes:
  crdb1_data:
  crdb2_data:
  crdb3_data:


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${CR_SUBNET:?please provide subnet range like `10.0.5`}.0/24
          gateway: ${CR_SUBNET}.254

```


 It seems that database produces wrong result when it read one table from remote node and union result from two nodes (by `explain analyze (verbose)`:


```diff
 planning time: 382µs
 execution time: 2ms
 distribution: full
 vectorized: true
 rows read from KV: 3 (96 B, 2 gRPC calls)
 cumulative time spent in KV: 660µs
 maximum memory usage: 50 KiB
 network usage: 304 B (4 messages)
 regions: r1, r3
 sql cpu time: 87µs
 
 • root
 │ columns: (c0)
 │
 ├── • limit
 │   │ columns: (c0)
 │   │ count: 2
 │   │
 │   └── • union all
 │       │ columns: (c0)
 │       │ ordering: +c0
> │       │ nodes: n1, n2
 │       │ regions: r1, r3
 │       │ actual row count: 2
 │       │ vectorized batch count: 2
 │       │ KV time: 357µs
 │       │ KV contention time: 0µs
 │       │ KV rows read: 2
 │       │ KV bytes read: 58 B
 │       │ KV gRPC calls: 1
 │       │ estimated max memory allocated: 20 KiB
 │       │ sql cpu time: 45µs
 │       │ MVCC step count (ext/int): 2/2
 │       │ MVCC seek count (ext/int): 2/2
 │       │ estimated row count: 1
 │       │
 │       ├── • render
 │       │   │ columns: (c0)
 │       │   │ render c0: false
 │       │   │
 │       │   └── • filter
 │       │       │ columns: ()
 │       │       │ nodes: n1
 │       │       │ regions: r1
 │       │       │ actual row count: 0
 │       │       │ vectorized batch count: 0
 │       │       │ sql cpu time: 15µs
 │       │       │ estimated row count: 0
 │       │       │ filter: @S1 IS NULL
 │       │       │
 │       │       └── • scan
 │       │             columns: ()
 │       │             nodes: n1
 │       │             regions: r1
 │       │             actual row count: 1
 │       │             vectorized batch count: 1
 │       │             KV time: 302µs
 │       │             KV contention time: 0µs
 │       │             KV rows read: 1
 │       │             KV bytes read: 38 B
 │       │             KV gRPC calls: 1
 │       │             estimated max memory allocated: 20 KiB
 │       │             sql cpu time: 16µs
 │       │             MVCC step count (ext/int): 1/1
 │       │             MVCC seek count (ext/int): 1/1
 │       │             estimated row count: 1 (100% of the table; stats collected 7 minutes ago)
 │       │             table: t1@idx1
 │       │             spans: FULL SCAN
 │       │
 │       └── • render
 │           │ columns: ("exists")
 │           │ render exists: false
 │           │
 │           └── • scan
 │                 columns: ()
> │                 nodes: n2
 │                 regions: r3
> │                 actual row count: 2
 │                 vectorized batch count: 2
 │                 KV time: 357µs
 │                 KV contention time: 0µs
 │                 KV rows read: 2
 │                 KV bytes read: 58 B
 │                 KV gRPC calls: 1
 │                 estimated max memory allocated: 20 KiB
 │                 sql cpu time: 30µs
 │                 MVCC step count (ext/int): 2/2
 │                 MVCC seek count (ext/int): 2/2
 │                 estimated row count: 1 - 2 (25% of the table; stats collected 7 minutes ago)
 │                 table: t2@t2_pkey
 │                 spans: LIMITED SCAN
> │                 limit: 1
 │
 └── • subquery
     │ id: @S1
     │ original sql: (SELECT 1)
     │ exec mode: one row
     │
     └── • values
           columns: ("?column?")
           nodes: n1
           regions: r1
           actual row count: 1
           vectorized batch count: 1
           sql cpu time: 24µs
           size: 1 column, 1 row
           row 0, expr 0: 1
(107 rows)


```
