### ISSUE TITLE
internal error: lists in SetPrivate are not all the same length in `buildSetProps()`

### ISSUE THREAD

**Issue by ycybfhb** [cockroachdb/cockroach#130398]
**Describe the problem**

internal error: lists in SetPrivate are not all the same length in `buildSetProps()`

**To Reproduce**

<details>
  <summary>SQL to init database</summary>

[init.sql.txt](https://github.com/user-attachments/files/16941629/init.sql.txt)

</details>

<details>
  <summary>SQL that causes error</summary>

```sql
select  
    subq_0.c0 as c0, 
    cast(coalesce(
      case when (subq_0.c2 between (select c_rqlsk_aj from t_bnqfnwa order by c_rqlsk_aj limit 1 offset 6)
             and ref_2.c_veh) then subq_1.c2 else (select c11 from t_rca order by c11 limit 1 offset 13)
           end
        , 
      subq_1.c0
      ) as float4) as c1, 
    case when (cast((cast(cast(null as oid) as oid) <= cast(cast(null as oid) as oid)) as bool)) then subq_1.c7 else subq_1.c0 end
       as c2, 
    ref_2.c_uuw5d832 as c3, 
    pg_catalog.json_strip_nulls(
      cast(cast(null as jsonb) as jsonb)) as c4, 
    (select c4 from t_rca order by c4 limit 1 offset 3)
       as c5, 
    subq_1.c3 as c6, 
    subq_1.c7 as c7, 
    ref_2.c_veh as c8, 
    case when (case when ((1425492021 between (select c_i9hbg1 from t_ow0g_ order by c_i9hbg1 limit 1 offset 1)
                 and subq_1.c8)) 
            or ((subq_1.c1 is NULL)) then -1711630245 else subq_1.c8 end
           in (
        select  
            ref_6.c5 as c0
          from 
            t_rca as ref_6
          where true
          order by c0 desc)) then subq_1.c5 else case when (EXISTS (
          select  
              ref_7.c4 as c0, 
              ref_7.c9 as c1, 
              ref_7.c2 as c2, 
              (select c_p6f922bie from t_y order by c_p6f922bie limit 1 offset 5)
                 as c3, 
              ref_7.c7 as c4, 
              ref_2.c_hl3s8ojsmc as c5, 
              ref_7.c7 as c6, 
              411099603 as c7, 
              ref_7.c1 as c8, 
              ref_2.c_uuw5d832 as c9, 
              subq_0.c2 as c10, 
              ref_2.c_d38l4v64 as c11
            from 
              t_rca as ref_7
            where (EXISTS (
              select  
                  ref_8.c_jqnxje42v as c0, 
                  ref_8.c_hdnu9xzja as c1, 
                  ref_8.c_tq as c2, 
                  ref_8.c_ywed as c3, 
                  subq_0.c4 as c4, 
                  ref_8.c_ywed as c5, 
                  (select c_n5 from t_ow0g_ order by c_n5 limit 1 offset 3)
                     as c6, 
                  ref_8.c_m50a as c7, 
                  subq_0.c0 as c8
                from 
                  t_y as ref_8
                where ((subq_1.c4 between subq_0.c4 and ref_7.c5)) 
                  or (((cast((cast(subq_1.c6 as text) NOT LIKE cast(ref_8.c_m50a as text)) as bool))) 
                    and ((ref_2.c_hl3s8ojsmc not in (
                      select  
                          (cast((cast(ref_9.c_uuw5d832 as text) !~ cast(ref_9.c_uuw5d832 as text)) as bool)) as c0
                        from 
                          t_bnqfnwa as ref_9
                        where (ref_9.c_uuw5d832 not like 'ylc%%3lc')))))
                order by c0, c1, c2, c3, c4, c5, c6, c7, c8 desc))
            limit 42)) then subq_1.c8 else subq_1.c8 end
         end
       as c9
  from 
    (((select  
              ref_0.c_ts7n as c0, 
              ref_0.c_ibhkt4ifda as c1, 
              ref_0.c_rqlsk_aj as c2, 
              ref_0.c_rqlsk_aj as c3, 
              1680898171 as c4
            from 
              t_bnqfnwa as ref_0
            where (cast((cast(cast(null as void) as void) IS DISTINCT FROM cast(cast(null as unknown) as unknown)) as bool))) as subq_0
        left outer join (select  
              ref_1.c_g9f9abs2 as c0, 
              ref_1.c_as7 as c1, 
              ref_1.c_g9f9abs2 as c2, 
              ref_1.c_l1 as c3, 
              ref_1.c_b3l3rlrs as c4, 
              ref_1.c_t9r1kl9y6m as c5, 
              ref_1.c_m50a as c6, 
              ref_1.c_as7 as c7, 
              ref_1.c_qokd as c8, 
              ref_1.c_t as c9
            from 
              t_y as ref_1
            where (((cast((cast(cast(null as jsonb) as jsonb) < cast(cast(null as jsonb) as jsonb)) as bool))) 
                or ((ref_1.c_t9r1kl9y6m not in (
                  ref_1.c_t9r1kl9y6m, cast(null as int4), ref_1.c_b3l3rlrs, ref_1.c_sc9oe0qu, ref_1.c_jqnxje42v)))) 
              and ((cast((cast(cast(null as "timestamptz") as "timestamptz") > cast(cast(null as date) as date)) as bool)))) as subq_1
        on (false))
      inner join t_bnqfnwa as ref_2
      on ((subq_0.c2 <> ( 
          select  
                subq_0.c0 as c0
              from 
                t_rca as ref_3
              where (cast((cast(cast(null as "timestamptz") as "timestamptz") <= cast(cast(null as "timestamp") as "timestamp")) as bool))
            union
            (
            select  
                subq_0.c2 as c0
              from 
                t_ow0g_ as ref_4
              where (EXISTS (
                select  
                    ref_2.c_d38l4v64 as c0, 
                    ref_4.c_gdyk as c1, 
                    ref_5.c_ui_l4yp as c2, 
                    ref_5.c_jqnxje42v as c3, 
                    (select c_ui_l4yp from t_y order by c_ui_l4yp limit 1 offset 3)
                       as c4, 
                    ref_5.c_m50a as c5, 
                    ref_5.c_jt8ydrx7 as c6, 
                    ref_5.c_b3l3rlrs as c7, 
                    ref_5.c_b3l3rlrs as c8, 
                    (select c_gdyk from t_ow0g_ order by c_gdyk limit 1 offset 1)
                       as c9, 
                    ref_5.c_g9f9abs2 as c10, 
                    ref_5.c_m50a as c11
                  from 
                    t_y as ref_5
                  where (ref_5.c_p6f922bie is not NULL)
                  order by c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11 asc))
            )
             limit 1))))
  where (cast((cast(cast(null as void) as void) IS DISTINCT FROM cast(cast(null as unknown) as unknown)) as bool))
union
(
select  
    subq_2.c4 as c0, 
    subq_2.c1 as c1, 
    case when (cast((cast(subq_2.c8 as int8) IS DISTINCT FROM cast(cast(null as "numeric") as "numeric")) as bool)) then subq_2.c1 else subq_2.c1 end
       as c2, 
    case when (cast((cast(cast(null as record) as record) != cast(cast(null as record) as record)) as bool)) then subq_2.c0 else (select c_ca from t_y order by c_ca limit 1 offset 2)
         end
       as c3, 
    cast(null as jsonb) as c4, 
    cast(coalesce(
      cast(subq_2.c8 as int8), 
      cast(subq_2.c4 as int8)
      ) as int8) as c5, 
    subq_2.c6 as c6, 
    (select c_vj_t3epb from t_ow0g_ order by c_vj_t3epb limit 1 offset 6)
       as c7, 
    subq_2.c8 as c8, 
    subq_2.c8 as c9
  from 
    (select  
          ref_10.c_deesne_t as c0, 
          (select c11 from t_rca order by c11 limit 1 offset 1)
             as c1, 
          ref_10.c_gdyk as c2, 
          ref_10.c_deesne_t as c3, 
          -1603328148 as c4, 
          ref_10.c_ie as c5, 
          ref_10.c_deesne_t as c6, 
          ref_10.c__sm6t8__m as c7, 
          ref_10.c_i9hbg1 as c8, 
          pg_catalog.set_config(
            cast(ref_10.c_gdyk as text), 
            cast(ref_10.c_gdyk as text), 
            cast((ref_10.c_gdyk like '%wwnhf') as bool)) as c9, 
          ref_10.c__sm6t8__m as c10
        from 
          t_ow0g_ as ref_10
        where (cast((cast(cast(null as "timestamp") as "timestamp") = cast(cast(null as "timestamptz") as "timestamptz")) as bool))
        order by c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10 asc) as subq_2
  where (EXISTS (
    select  
        ref_11.c_ie as c0, 
        ref_11.c_deesne_t as c1, 
        ref_11.c_gdyk as c2, 
        subq_2.c4 as c3, 
        ref_11.c_deesne_t as c4, 
        ref_11.c_gdyk as c5, 
        ref_11.c_deesne_t as c6, 
        pg_catalog.asind(
          cast(case when (cast((cast(null as "box2d") IS DISTINCT FROM cast(null as "box2d")) as bool)) then cast(null as float8) else 66.73 end
             as float8)) as c7, 
        ref_11.c_ie as c8, 
        subq_2.c1 as c9, 
        ref_11.c_i9hbg1 as c10, 
        ref_11.c_deesne_t as c11
      from 
        t_ow0g_ as ref_11
      where true))
)
 limit 137;

```

</details>

**Expected behavior**

Expect no crashes

**Additional data / screenshots**

Here is the crash stack trace:

```
Hook early check failed: Database execute error: XX000, ERROR: internal error: lists in SetPrivate are not all the same length. new:7, left:7, right:8
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:739: buildSetProps()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:711: buildUnionAllProps()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go:21733: MemoizeUnionAll()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:11320: ConstructUnionAll()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:1860: exploreSemiJoin()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:38: exploreGroupMember()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:185: exploreGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:537: optimizeGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:300: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:312: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:312: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:312: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:312: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:312: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:309: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:622: optimizeScalarExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:312: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:579: optimizeGroupMember()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:524: optimizeGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:300: optimizeExpr()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:579: optimizeGroupMember()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:524: optimizeGroup()
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:270: Optimize()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:804: makeQueryIndexRecommendation()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:612: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:250: makeOptimizerPlan()
;
Error while executing the query
extra info: cost: 816ms
```

**Environment:**

 - CockroachDB version: v24.1.0
 - Server OS: `Linux a002 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - Client app: postgresql odbc/psql

docker compose file:
```
version: '3.5'

services:
  crdb1:
    image: cockroachdb/cockroach:v24.1.0
    command: "start --advertise-addr=crdb1:26357 --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb1_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.11

  crdb2:
    image: cockroachdb/cockroach:v24.1.0
    command: "start --advertise-addr=crdb2:26357 --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb2_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.12

  crdb3:
    image: cockroachdb/cockroach:v24.1.0
    command: "start --advertise-addr=crdb3:26357 --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb3_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.13

  crdb_single:
    image: cockroachdb/cockroach:v24.1.0

    command: start-single-node --insecure
    volumes:
      - "crdb_single_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: 10.0.5.21

volumes:
  crdb1_data:
  crdb2_data:
  crdb3_data:
  crdb_single_data:


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.5.0/24
          gateway: 10.0.5.254
```

#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned possible vulnerabilities that may lead to database crashes.

Jira issue: CRDB-42032
