### ISSUE TITLE
internal error: cannot map variable 17 to an indexed var

### ISSUE THREAD

**Issue by r33s3n6** [cockroachdb/cockroach#134066]
**Describe the problem**
internal error: cannot map variable 17 to an indexed var

**To Reproduce**
```sql
create table t1 (c0 int4 primary key);
insert into t1 values (1);

select 1 
from
  (select 
    c0 as a1,
    (select null from
        (select case
                    when (ref_1.c0 between ref_1.c0 and ref_2.c0) 
                    then 1
                    else ref_1.c0
                end as b0
         from (
                 (select c0::int8 as c0 from (select c0 from t1)) as ref_1
               cross join t1 as ref_2))
      order by b0 limit 1 offset 4) as a0

   from t1
   where (false)) as subq_1
where (case
           when
                  (select (null::timestamptz is distinct from null::timestamp)
                   from
                     (select c0 from (select c0 from t1) where false) as ref_2
                   where (((subq_1.a1)::int8 between subq_1.a0 and ref_2.c0))) 
           then subq_1.a0
           else subq_1.a1
       end between subq_1.a1 and subq_1.a1);
```

error log:
```
ERROR:  internal error: cannot map variable 17 to an indexed var
DETAIL:  stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/scalar.go:162: indexedVar()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1088: buildProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:207: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:947: buildSelect()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:204: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1053: buildProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:207: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:298: build()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:240: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:944: runExecBuilder()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:323: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2298: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1848: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1181: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3436: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2316: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2321: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2238: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:963: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:256: processCommands()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1136: func4()
src/runtime/asm_amd64.s:1695: goexit()

```
**Environment:**
 - CockroachDB version: 24.2.4
 - Server OS: Ubuntu 22.04
 - Client app: psql

docker compose file:
```yaml
x-service-defaults: &service_defaults
  image: cockroachdb/cockroach:v24.2.4

services:
  crdb1:
    <<: *service_defaults
    command: "start --advertise-addr=crdb1:26357 --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb1_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.11

  crdb2:
    <<: *service_defaults
    command: "start --advertise-addr=crdb2:26357 --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb2_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.12

  crdb3:
    <<: *service_defaults
    command: "start --advertise-addr=crdb3:26357 --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb3_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.13

  crdb_single:
    <<: *service_defaults
    command: start-single-node --insecure
    volumes:
      - "crdb_single_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.21

volumes:
  crdb1_data:
  crdb2_data:
  crdb3_data:
  crdb_single_data:


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${CR_SUBNET:?please provide subnet range like `10.0.5`}.0/24
          gateway: ${CR_SUBNET}.254
```

**about us**
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned possible vulnerabilities that may lead to database internal error.
