### ISSUE TITLE
internal error: column 21 not in input

### ISSUE THREAD

**Issue by r33s3n6** [cockroachdb/cockroach#134058]
**Describe the problem**
internal error: column 21 not in input

**To Reproduce**
```sql
create table t1 (c1 int4 primary key);
insert into t1 (c1) values (1);

SELECT
  1
FROM
  (select (select 'ejm7:23:j' from t1 limit 1) as c_h3c6zmz5um
        from t1 as ref_2) as subq_1
WHERE
  (EXISTS (
    select 1 from 
        (t1 as ref_3 cross join t1 as ref_4)
      where ((case when ( 
            select  
                  ref_4.c1
                from 
                  t1 as ref_5
                where (subq_1.c_h3c6zmz5um like '_')
              union all
              (
              select  
                  ref_4.c1
                from 
                  ( select 1 where (((cast(null as "timestamptz")) = null))) as ref_8
                where true
              )
               limit 1) = 1 then 0 else ref_4.c1 end
          ) between 0 and ref_3.c1)
      ));

```

error log:
```
ERROR:  internal error: column 21 not in input
DETAIL:  newRightSide:
project
 ├── columns: c1:9!null c1:12!null c1:21
 ├── immutable
 ├── stats: [rows=111111.1]
 ├── cost: 6598.52847
 ├── key: (9,12)
 ├── fd: (9,12)-->(21)
 ├── prune: (9,12,21)
 └── inner-join (cross)
      ├── columns: ref_3.c1:9!null ref_4.c1:12!null column25:25!null
      ├── immutable
      ├── stats: [rows=111111.1, distinct(9)=1000, null(9)=0, distinct(25)=1, null(25)=0]
      ├── cost: 5487.39736
      ├── key: (9,12)
      ├── fd: (12)-->(25)
      ├── scan t1 [as=ref_3]
      │    ├── columns: ref_3.c1:9!null
      │    ├── stats: [rows=1000, distinct(9)=1000, null(9)=0]
      │    ├── cost: 1048.22
      │    ├── key: (9)
      │    ├── prune: (9)
      │    └── unfiltered-cols: (9-11)
      ├── project
      │    ├── columns: column25:25 ref_4.c1:12!null
      │    ├── immutable
      │    ├── stats: [rows=333.3333, distinct(25)=1, null(25)=0]
      │    ├── cost: 1087.46667
      │    ├── key: (12)
      │    ├── fd: (12)-->(25)
      │    ├── prune: (12,25)
      │    ├── select
      │    │    ├── columns: ref_4.c1:12!null c1:21
      │    │    ├── immutable
      │    │    ├── stats: [rows=333.3333, distinct(12,21)=1, null(12,21)=0]
      │    │    ├── cost: 1080.78
      │    │    ├── key: (12)
      │    │    ├── fd: (12)-->(21)
      │    │    ├── left-join (cross)
      │    │    │    ├── columns: ref_4.c1:12!null c1:21
      │    │    │    ├── multiplicity: left-rows(exactly-one), right-rows(zero-or-more)
      │    │    │    ├── stats: [rows=1000, distinct(12,21)=1, null(12,21)=0]
      │    │    │    ├── cost: 1070.75
      │    │    │    ├── key: (12)
      │    │    │    ├── fd: (12)-->(21)
      │    │    │    ├── prune: (12,21)
      │    │    │    ├── unfiltered-cols: (12-14)
      │    │    │    ├── scan t1 [as=ref_4]
      │    │    │    │    ├── columns: ref_4.c1:12!null
      │    │    │    │    ├── stats: [rows=1000, distinct(12)=1000, null(12)=0]
      │    │    │    │    ├── cost: 1048.22
      │    │    │    │    ├── key: (12)
      │    │    │    │    ├── prune: (12)
      │    │    │    │    └── unfiltered-cols: (12-14)
      │    │    │    ├── values
      │    │    │    │    ├── columns: c1:21!null
      │    │    │    │    ├── cardinality: [0 - 0]
      │    │    │    │    ├── stats: [rows=0, distinct(21)=0, null(21)=0]
      │    │    │    │    ├── cost: 0.01
      │    │    │    │    ├── key: ()
      │    │    │    │    ├── fd: ()-->(21)
      │    │    │    │    └── prune: (21)
      │    │    │    └── filters (true)
      │    │    └── filters
      │    │         └── CASE WHEN c1:21 = 1 THEN 0 ELSE ref_4.c1:12::INT8 END >= 0 [outer=(12,21), immutable]
      │    └── projections
      │         └── CASE WHEN c1:21 = 1 THEN 0 ELSE ref_4.c1:12::INT8 END [as=column25:25, outer=(12,21), immutable]
      └── filters
           └── ref_3.c1:9 >= column25:25 [outer=(9,25), constraints=(/9: (/NULL - ]; /25: (/NULL - ])]
stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:76: getNodeColumnOrdinal()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1030: applySimpleProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1065: buildProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:207: buildRelational()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:298: build()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:240: Build()
github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1235: func1()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:251: runNextRightSideIteration()
github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:222: Next()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:216: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecutils/operator.go:157: Next()
github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/colexec/colexecbase/const.eg.go:368: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/simple_project.go:124: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:152: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:282: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:932: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1994: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1708: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1711: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2427: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1974: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1181: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3436: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2316: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2321: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2238: run()

```
**Environment:**
 - CockroachDB version: 24.2.4
 - Server OS: Ubuntu 22.04
 - Client app: psql

docker compose file:
```yaml
x-service-defaults: &service_defaults
  image: cockroachdb/cockroach:v24.2.4

services:
  crdb1:
    <<: *service_defaults
    command: "start --advertise-addr=crdb1:26357 --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb1_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.11

  crdb2:
    <<: *service_defaults
    command: "start --advertise-addr=crdb2:26357 --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb2_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.12

  crdb3:
    <<: *service_defaults
    command: "start --advertise-addr=crdb3:26357 --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357"
    volumes:
      - "crdb3_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.13

  crdb_single:
    <<: *service_defaults
    command: start-single-node --insecure
    volumes:
      - "crdb_single_data:/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.21

volumes:
  crdb1_data:
  crdb2_data:
  crdb3_data:
  crdb_single_data:


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${CR_SUBNET:?please provide subnet range like `10.0.5`}.0/24
          gateway: ${CR_SUBNET}.254
```

**about us**
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned possible vulnerabilities that may lead to database internal error.
