### ISSUE TITLE
Docker init script does not respect COCKROACH_DATABASE when running sql files in docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by mecab** [cockroachdb/cockroach#137735]
**Describe the problem**

The init script in the docker image runs `.sql` files inside `docker-entrypoint-initdb.d`. But it does not respect `COCKROACH_DATABASE` so the operations (i.e., creating tables) are always done against `defaultdb`.

**To Reproduce**

Run the official docker image with mounting `docker-entrypoint-initdb.d` containing any `.sql` files.

This is an example docker-compose.

```
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest-v24.3
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - COCKROACH_USER=user
      - COCKROACH_PASSWORD=password
      - COCKROACH_DATABASE=mydatabase
```

Place `001_create_table.sql` as 

```sql
CREATE TABLE new_table (
    id VARCHAR(26) PRIMARY KEY
);
```

**Expected behavior**
`new_table` is created for `mydatabase`

**Actual behavior**
`new_table` is created for `defaultdb`

**Environment:**
 - CockroachDB version [e.g. 2.0.x]: 24.3
 - Server OS: Ubuntu on WSL2

**Additional context**
I have not checked Postgres init script, which CockroachDB's one seemed to be based on, behaves POSTGRES_DATABASE. But anyway it is more useful when it respects the variable when running the queries.

Also, I am happy to raise a PR to fix it if the team want to fix it.

Thank you for developing and maintaining a great database!

Jira issue: CRDB-45721
