### ISSUE TITLE
Orchestrate a secure CockroachDB cluster with Kubernetes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#13857]
We need to identify engineering work necessary to orchestrate a secure CockroachDB cluster with Kubernetes. 

@petermattis

**Comment by jseldess** [comment]
@a-robinson, please fill in more details about why this doesn't work out of the box, when you have time.

**Comment by a-robinson** [comment]
The main issue here is getting a different cert to each node. Kubernetes has a feature called "Secrets" for things like distributing certs to pods in a cluster, but it isn't integrated (and isn't likely to be soon) with the StatefulSets feature that we're using in a way that lets us distribute a different cert to each pod (see kubernetes/kubernetes#28446 (comment)). All we'd be able to do is give each pod the same cert, which doesn't line up with how CockroachDB's security is currently designed.

Some engineering effort will be needed to work around this limitation. It could mean that we use a different Kubernetes configuration for secure clusters that doesn't use PetSets, or that we stand up a separate service in the cluster for creating and distributing certs. Or that we modify CockroachDB to use symmetric certs on the nodes, but that would require its own conversation. That's what some other services do, for example this moderately popular guide for running secured Consul on Kubernetes.

**Comment by jseldess** [comment]
It's possible to use the same cert for multiple nodes, so for now, I'm just going to write up a tutorial using that approach. @a-robinson, feel free to leave this open if we expect to make changes to enable node-specific certs with Kubernetes.

**Comment by mberhault** [comment]
I should have this done this week. the secure config in https://github.com/cockroachdb/cockroach/tree/master/cloud/kubernetes is mostly correct, but I need to finish my improvements to the init container docker image to allow persistent certificate storage (so that you won't have to re-approve certs when nodes move or when you add clients).

**Comment by fire** [comment]
https://docs.openshift.com/container-platform/3.5/dev_guide/secrets.html#service-serving-certificate-secrets Allows generation of certificates via openshift origin (kubernetes). It looks useful for this case.

**Comment by fire** [comment]
Note that one service certificate is generated for all the nodes. 

If you want a client certificate you'll need to use manual commands.

**Comment by fire** [comment]
Interesting find. https://github.com/kelseyhightower/certificate-init-container

Per pod certificates.

**Comment by fire** [comment]
https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/#approval-controller

This doc describes auto approval for both clients and server (feature gated).

**Comment by mberhault** [comment]
Certificates (both client and node) work with kubernetes, we just haven't written up the proper docs yet, just the basic ones in https://github.com/cockroachdb/cockroach/tree/master/cloud/kubernetes
There's still some work to do (one big caveat right now is that clients can only start with 1 replica to avoid conflicting certificate requests, once approved they can scale to whatever is desired) and a lot more testing, but the broad lines are there.

**Comment by fire** [comment]
Is it possible to write instructions of using insecure-experimental-approve-all-kubelet-csrs-for-group?

In kube 1.7 there's a rbac version, but that's not ready yet.

**Comment by cuongdo** [comment]
@mberhault is this still happening before 1.1?

**Comment by jseldess** [comment]
Secure k8 docs are next on my list. I do expect them to be done for 1.1.

**Comment by mberhault** [comment]
Docs issue is: https://github.com/cockroachdb/docs/issues/875
Closing this one.

**Comment by diwakar-s-maurya** [comment]
I am new to kubernetes and cockroachdb. Can someone explain what could go wrong if i start the cockroachdb cluster using this yaml? It is similar to [this](https://raw.githubusercontent.com/cockroachdb/cockroach/master/cloud/kubernetes/cockroachdb-statefulset.yaml) with changes in 'command' label of 'cockroachdb' container.
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cockroachdb
spec:
  serviceName: "cockroachdb"
  replicas: 2
  template:
    metadata:
      labels:
        app: cockroachdb
    spec:
      # Init containers are run only once in the lifetime of a pod, before
      # it's started up for the first time. It has to exit successfully
      # before the pod's main containers are allowed to start.
      # This particular init container does a DNS lookup for other pods in
      # the set to help determine whether or not a cluster already exists.
      # If any other pods exist, it creates a file in the cockroach-data
      # directory to pass that information along to the primary container that
      # has to decide what command-line flags to use when starting CockroachDB.
      # This only matters when a pod's persistent volume is empty - if it has
      # data from a previous execution, that data will always be used.
      #
      # If your Kubernetes cluster uses a custom DNS domain, you will have
      # to add an additional arg to this pod: "-domain=<your-custom-domain>"
      initContainers:
      - name: bootstrap
        image: cockroachdb/cockroach-k8s-init:0.2
        imagePullPolicy: IfNotPresent
        args:
        - "-on-start=/on-start.sh"
        - "-service=cockroachdb"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - cockroachdb
              topologyKey: kubernetes.io/hostname
      containers:
      - name: cockroachdb
        image: cockroachdb/cockroach:v1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 26257
          name: grpc
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: datadir
          mountPath: /cockroach/cockroach-data
        volumeMounts:
        - name: cockroach-config
          mountPath: /certs
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            # The use of qualified `hostname -f` is crucial:
            # Other nodes aren't able to look up the unqualified hostname.

            ls /certs

            /cockroach/cockroach cert create-node \
              localhost \
              $(hostname -f) \
              cockroachdb-public \
              --certs-dir=/certs \
              --ca-key=/certs/ca.key

            rm /certs/ca.key
            ls /certs

            CRARGS=("start" "--logtostderr" "--certs-dir" "/certs" "--host" "$(hostname -f)" "--http-host" "0.0.0.0" "--cache" "25%" "--max-sql-memory" "25%")
            # We only want to initialize a new cluster (by omitting the join flag)
            # if we're sure that we're the first node (i.e. index 0) and that
            # there aren't any other nodes running as part of the cluster that
            # this is supposed to be a part of (which indicates that a cluster
            # already exists and we should make sure not to create a new one).
            # It's fine to run without --join on a restart if there aren't any
            # other nodes.
            if [ ! "$(hostname)" == "cockroachdb-0" ] || \
               [ -e "/cockroach/cockroach-data/cluster_exists_marker" ]
            then
              # We don't join cockroachdb in order to avoid a node attempting
              # to join itself, which currently doesn't work
              # (https://github.com/cockroachdb/cockroach/issues/9625).
              CRARGS+=("--join" "cockroachdb-public")
            fi
            exec /cockroach/cockroach ${CRARGS[*]}
      # No pre-stop hook is required, a SIGTERM plus some time is all that's
      # needed for graceful shutdown of a node.
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: datadir
      - name: cockroach-config
        secret:
          secretName: cockroachdb-config
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi
```

and before deploying it, running this
```bash
mkdir securedir
chmod -R 700 securedir

cockroach cert create-ca \
--certs-dir=securedir \
--ca-key=securedir/ca.key

kubectl create secret generic cockroachdb-config --from-file=./securedir/ca.crt --from-file=./securedir/ca.key
```
