### ISSUE TITLE
`to_regrole` produces `NULL` unexpectedly when distributed processing

### ISSUE THREAD

**Issue by r33s3n6** [cockroachdb/cockroach#144384]
**Describe the problem**
`to_regrole` produced wrong result in distributed plan (when having multiple region, and executing SQL on a remote node)

**To Reproduce**

```sql
create table t1 ( 
pkey int4 ,
c1 text not null ,
primary key(pkey),
unique(pkey)
);

ALTER TABLE t1 CONFIGURE ZONE 
  USING num_replicas = 1, constraints = '[+region=r3]', lease_preferences = '[[+region=r3]]';

insert into t1 (pkey, c1) values (-1, 'root');

select 
  c1 as c1,
  pg_catalog.to_regrole(c1) as c2
FROM t1;
```
result:
```
  c1  | c2 
------+----
 root | 
(1 row)
```
However,
```sql
cr11=> select pg_catalog.to_regrole('root');
 to_regrole 
------------
 root
(1 row)
```
### wrong distributed execution when executing query on nodes other than `r3`
```
cr11=> select 
  c1 as c1,
  pg_catalog.to_regrole(c1) as c2
FROM t1;
  c1  | c2 
------+----
 root | 
(1 row)
```

```
 planning time: 667µs
 execution time: 3ms
 distribution: full
 vectorized: true
 plan type: custom
 rows decoded from KV: 1 (35 B, 1 gRPC calls)
 cumulative time spent in KV: 719µs
 maximum memory usage: 50 KiB
 network usage: 248 B (3 messages)
 regions: r1, r3
 sql cpu time: 257µs
 isolation level: serializable
 priority: normal
 quality of service: regular
 
 • render
 │
 └── • scan
       nodes: n5
       regions: r3
       actual row count: 1
       KV time: 719µs
       KV contention time: 0µs
       KV rows decoded: 1
       KV bytes read: 35 B
       KV gRPC calls: 1
       estimated max memory allocated: 20 KiB
       sql cpu time: 109µs
       estimated row count: 1 (100% of the table; stats collected 19 seconds ago)
       table: t1@t1_pkey
       spans: FULL SCAN
(31 rows)
```

### correct local execution when executing query on nodes `r3`
```
cr11=> select 
  c1 as c1,
  pg_catalog.to_regrole(c1) as c2
FROM t1;
  c1  |  c2  
------+------
 root | root
(1 row)
```
```
 planning time: 405µs
 execution time: 8ms
 distribution: full
 vectorized: true
 plan type: generic, reused
 rows decoded from KV: 1 (35 B, 1 gRPC calls)
 cumulative time spent in KV: 7ms
 maximum memory usage: 30 KiB
 network usage: 0 B (0 messages)
 regions: r3
 sql cpu time: 407µs
 isolation level: serializable
 priority: normal
 quality of service: regular
 
 • render
 │
 └── • scan
       nodes: n5
       regions: r3
       actual row count: 1
       KV time: 7ms
       KV contention time: 0µs
       KV rows decoded: 1
       KV bytes read: 35 B
       KV gRPC calls: 1
       estimated max memory allocated: 20 KiB
       sql cpu time: 407µs
       estimated row count: 1 (100% of the table; stats collected 3 minutes ago)
       table: t1@t1_pkey
       spans: FULL SCAN
(31 rows)
```

**Environment:**
 - CockroachDB version: 23.2.23
 - Server OS: `Linux a002 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - Client app: psql

docker compose file:
```
x-service-defaults: &service_defaults
  image: ${CR_IMAGE:?please provide the image name}

services:
  crdb1:
    <<: *service_defaults
    command: "start --advertise-addr=crdb1:26357 --locality=region=r1,zone=r1a --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.11

  crdb2:
    <<: *service_defaults
    command: "start --advertise-addr=crdb2:26357 --locality=region=r2,zone=r2a --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.12

  crdb3:
    <<: *service_defaults
    command: "start --advertise-addr=crdb3:26357 --locality=region=r3,zone=r3a --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.13

  crdb4:
    <<: *service_defaults
    command: "start --advertise-addr=crdb4:26357 --locality=region=r4,zone=r4a --http-addr=crdb4:8080 --listen-addr=crdb4:26357 --sql-addr=crdb4:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.14

  crdb5:
    <<: *service_defaults
    command: "start --advertise-addr=crdb5:26357 --locality=region=r5,zone=r5a --http-addr=crdb5:8080 --listen-addr=crdb5:26357 --sql-addr=crdb5:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.15

  crdb_single:
    <<: *service_defaults
    command: start-single-node --insecure
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.21


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${CR_SUBNET:?please provide subnet range like `10.0.5`}.0/24
          gateway: ${CR_SUBNET}.254


```

#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned possible vulnerabilities that may lead to database logic error.

Jira issue: CRDB-49363
