### ISSUE TITLE
`to_char` produced unexpected result with timestamptz

### ISSUE THREAD

**Issue by r33s3n6** [cockroachdb/cockroach#145026]
**Describe the problem**
`to_char` produced unexpected result with timestamptz.

**To Reproduce**

```sql
--- init database
create table t0 (c4 text);
insert into t0 values ('YYYY-MM-DD HH24:MI:SS.USTZH:TZM');

--- error sql
with tz as (SHOW TIME ZONE)
select 
    ref_0.c4 as a1,
    pg_catalog.to_char(('0001-01-01 00:03:00.000000+01:00')::timestamptz, ref_0.c4) as a2,
    pg_catalog.to_char(('0001-01-01 00:03:00.000000+01:00')::timestamptz, 'YYYY-MM-DD HH24:MI:SS.USTZH:TZM') as a3,
    (select timezone from tz) as a4
  from t0 as ref_0
order by 1,2,3,4
;
```

**Wrong result**:
(`a2` != `a3`)
```
               a1                |                a2                |                a3                | a4  
---------------------------------+----------------------------------+----------------------------------+-----
 YYYY-MM-DD HH24:MI:SS.USTZH:TZM | 0000-12-31 23:03:00.000000+00:00 | 0001-01-01 00:03:00.000000+01:00 | UTC
(1 row)
```
plan:
```
                                          info                                           
-----------------------------------------------------------------------------------------
 planning time: 758µs
 execution time: 4ms
 distribution: full
 vectorized: true
 plan type: custom
 rows decoded from KV: 1 (70 B, 1 KVs, 1 gRPC calls)
 cumulative time spent in KV: 1ms
 maximum memory usage: 60 KiB
 network usage: 488 B (3 messages)
 regions: r1, r5
 sql cpu time: 412µs
 isolation level: serializable
 priority: normal
 quality of service: regular
 
 • root
 │ columns: (a1, a2, a3, a4)
 │
 ├── • sort
 │   │ columns: (a1, a2, a3, a4)
 │   │ nodes: n3
 │   │ regions: r5
 │   │ actual row count: 1
 │   │ vectorized batch count: 1
 │   │ estimated max memory allocated: 10 KiB
 │   │ estimated max sql temp disk usage: 0 B
 │   │ sql cpu time: 42µs
 │   │ estimated row count: 1
 │   │ order: +c4,+a4
 │   │
 │   └── • render
 │       │ columns: (a2, a3, a4, c4)
 │       │ render a2: to_char('0001-01-01 00:03:00+01', c4)
 │       │ render a3: '0001-01-01 00:03:00.000000+01:00'
 │       │ render a4: @S1
 │       │ render c4: c4
 │       │
 │       └── • scan
 │             columns: (c4)
 │             nodes: n3
 │             regions: r5
 │             actual row count: 1
 │             vectorized batch count: 1
 │             KV time: 1ms
 │             KV contention time: 0µs
 │             KV rows decoded: 1
 │             KV pairs read: 1
 │             KV bytes read: 70 B
 │             KV gRPC calls: 1
 │             estimated max memory allocated: 20 KiB
 │             sql cpu time: 87µs
 │             MVCC step count (ext/int): 1/1
 │             MVCC seek count (ext/int): 1/1
 │             estimated row count: 1 (100% of the table; stats collected 2 minutes ago)
 │             table: t0@t0_pkey
 │             spans: FULL SCAN
 │
 └── • subquery
     │ id: @S1
     │ original sql: (SELECT timezone FROM tz)
     │ exec mode: one row
     │
     └── • max1row
         │ columns: (timezone)
         │ nodes: n1
         │ regions: r1
         │ actual row count: 1
         │ vectorized batch count: 1
         │ sql cpu time: 70µs
         │ estimated row count: 1
         │
         └── • render
             │ columns: (timezone)
             │ render timezone: timezone
             │
             └── • show
                   columns: (timezone)
                   nodes: n1
                   regions: r1
                   actual row count: 1
                   vectorized batch count: 1
                   sql cpu time: 26µs
                   estimated row count: 10 (missing stats)
(83 rows)

```

**Environment:**
 - CockroachDB version: 23.2.23
 - Server OS: `Linux a002 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - Client app: psql

docker compose file:
```
x-service-defaults: &service_defaults
  image: ${CR_IMAGE:?please provide the image name}

services:
  crdb1:
    <<: *service_defaults
    command: "start --advertise-addr=crdb1:26357 --locality=region=r1,zone=r1a --http-addr=crdb1:8080 --listen-addr=crdb1:26357 --sql-addr=crdb1:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.11

  crdb2:
    <<: *service_defaults
    command: "start --advertise-addr=crdb2:26357 --locality=region=r2,zone=r2a --http-addr=crdb2:8080 --listen-addr=crdb2:26357 --sql-addr=crdb2:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.12

  crdb3:
    <<: *service_defaults
    command: "start --advertise-addr=crdb3:26357 --locality=region=r3,zone=r3a --http-addr=crdb3:8080 --listen-addr=crdb3:26357 --sql-addr=crdb3:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.13

  crdb4:
    <<: *service_defaults
    command: "start --advertise-addr=crdb4:26357 --locality=region=r4,zone=r4a --http-addr=crdb4:8080 --listen-addr=crdb4:26357 --sql-addr=crdb4:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.14

  crdb5:
    <<: *service_defaults
    command: "start --advertise-addr=crdb5:26357 --locality=region=r5,zone=r5a --http-addr=crdb5:8080 --listen-addr=crdb5:26357 --sql-addr=crdb5:26257 --insecure --join=crdb1:26357,crdb2:26357,crdb3:26357,crdb4:26357,crdb5:26357"
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.15

  crdb_single:
    <<: *service_defaults
    command: start-single-node --insecure
    volumes:
      - "/cockroach/cockroach-data"
    networks:
      crnet:
        ipv4_address: ${CR_SUBNET}.21


networks:
  crnet:
    driver: bridge
    ipam:
      config:
        - subnet: ${CR_SUBNET:?please provide subnet range like `10.0.5`}.0/24
          gateway: ${CR_SUBNET}.254


```

#### about us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned possible vulnerabilities that may lead to database logic error.

Jira issue: CRDB-49654
