### ISSUE TITLE
Disabling Telemetry logging doesn't take effect

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/cockroach#148838]
**Describe the problem**
I'd like to disable Telemetry logging and when the new log config is applied, telemetry log are still being emitted.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
1) deploy a cluster using the logging config
```
      file-defaults:
        max-file-size: 10MiB
        max-group-size: 500MiB
        file-permissions: 644
        buffered-writes: false
        buffering:
          max-staleness: 1s
          flush-trigger-size: 256KiB
          max-buffer-size: 50MiB
        filter: INFO
        format: crdb-v2
        redact: false
        redactable: true
        exit-on-error: true
        auditable: false
      sinks:
        file-groups:
          default:
            channels:
              INFO: [DEV, OPS]
              WARNING: all except [DEV, OPS]
          health:
            channels: [HEALTH]
          kv-distribution:
            channels: [KV_DISTRIBUTION]
          pebble:
            channels: [STORAGE]
          security:
            channels: [PRIVILEGES, USER_ADMIN]
          sql-audit:
            channels: [SENSITIVE_ACCESS]
          sql-auth:
            channels: [SESSIONS]
          sql-exec:
            channels: [SQL_EXEC]
          sql-slow:
            channels: [SQL_PERF]
          sql-slow-internal-only:
            channels: [SQL_INTERNAL_PERF]
          telemetry:
            channels: [TELEMETRY]
            max-file-size: 100KiB
            max-group-size: 1.0MiB      
        stderr:
          channels: all
          filter: NONE
          redact: false
          redactable: true
          exit-on-error: true
      capture-stray-errors:
        enable: true
        max-group-size: 500MiB
```
Verify telemetry logs are being generated such as store stats or hot range stats.

2) remove telemetry section from the above
```
          telemetry:
            channels: [TELEMETRY]
            max-file-size: 100KiB
            max-group-size: 1.0MiB  
```
and applied the config. Verified using cockroach debug check-log-config as below.
```
bash-5.1$ cockroach debug check-log-config --log-config-file=log-config/log-config.yaml
# configuration after validation:
file-defaults:
  dir: /cockroach/cockroach-data/logs
  max-file-size: 10MiB
  max-group-size: 500MiB
  file-permissions: "0644"
  buffered-writes: false
  filter: INFO
  format: crdb-v2
  redact: false
  redactable: true
  exit-on-error: true
  auditable: false
  buffering:
    max-staleness: 1s
    flush-trigger-size: 256KiB
    max-buffer-size: 50MiB
    format: newline
fluent-defaults:
  filter: INFO
  format: json-fluent-compact
  redact: false
  redactable: true
  exit-on-error: false
  auditable: false
  buffering:
    max-staleness: 5s
    flush-trigger-size: 1.0MiB
    max-buffer-size: 50MiB
    format: newline
http-defaults:
  method: POST
  unsafe-tls: false
  timeout: 2s
  disable-keep-alives: false
  compression: gzip
  filter: INFO
  format: json-compact
  redact: false
  redactable: true
  exit-on-error: false
  auditable: false
  buffering:
    max-staleness: 5s
    flush-trigger-size: 1.0MiB
    max-buffer-size: 50MiB
    format: newline
sinks:
  file-groups:
    default:
      channels: {INFO: [DEV, OPS], WARNING: [HEALTH, STORAGE, SESSIONS, SQL_SCHEMA, USER_ADMIN, PRIVILEGES, SENSITIVE_ACCESS, SQL_EXEC, SQL_PERF, SQL_INTERNAL_PERF, TELEMETRY, KV_DISTRIBUTION]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    health:
      channels: {INFO: [HEALTH]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    kv-distribution:
      channels: {INFO: [KV_DISTRIBUTION]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    pebble:
      channels: {INFO: [STORAGE]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    security:
      channels: {INFO: [USER_ADMIN, PRIVILEGES]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-audit:
      channels: {INFO: [SENSITIVE_ACCESS]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-auth:
      channels: {INFO: [SESSIONS]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-exec:
      channels: {INFO: [SQL_EXEC]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-slow:
      channels: {INFO: [SQL_PERF]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-slow-internal-only:
      channels: {INFO: [SQL_INTERNAL_PERF]}
      dir: /cockroach/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 500MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
  stderr:
    filter: NONE
    format: crdb-v2-tty
    redact: false
    redactable: true
    exit-on-error: true
    buffering:
      max-staleness: 1s
      flush-trigger-size: 256KiB
      max-buffer-size: 50MiB
      format: newline
capture-stray-errors:
  enable: true
  dir: /cockroach/cockroach-data/logs
  max-group-size: 500MiB

# graphical diagram URL:
http://www.plantuml.com/plantuml/uml/X5PVRzew57y_dyBYwTw7tEBm9z27gpBmscWK64dP9ar28J5jL3Tk7QTRDVMxJx59CWVCdd9-Vwpcv1p_obKk8o6B9mQCxYMI78dq_a6Y91KqbYdF8EPFppoZcKGvBqHCS_GB_laNpSYcV2nNGVcu8PDvU5DMGRXSJww9AaaG-Ck5CWIVvzjWUaDk9oMw2yXwEvdT-eiIhTR-nf-JQwATP17ueRyXsybqIeBwDFbAfbMz8kkFLUqlGh9UJ1eo97DoIyBrjn9yscndVX2k_GzteRzSGCnuaQ1SYkWDHJdggEfxHeNW8k_0ExmKjA0ebmaL0k989EXvkyNAk-VYAPANiKXspglRgLLNgocJL5n-QVYUXUzR-8657rfupyAFBFpOmkEkJS0smTOojlMC-sS_8HwSbuVdPU-yF3elZyzFjtjU_ijkk2VbICXq7yKIxLEcRXJQSvPGWJeNCOyV1O_YXwPoaaX65upVvvtIgWwXlVx3jUa_nkyxjUYQelD08oPRdbxBy_Zg96akHRehofjlclijypFTxHWrFOEM9wTn8LBvPhg6RTSBSw8YIQLfyqxQsZsCJhZeJngRhl49Lyxu3zDrk0V7DYVD91LPn1oUCRCR7HIgR9rLmi7x3kym8nlaEF-hZOFbAcY03iyAkt28q8heGHMa5TE79auhRW1Dg5RS49fehJWFsW5RAIEeOhPYnb25RVsoNJZAt5h3K4TlpRdGIk1QwO4ArXBkCQWOhR-82iy_KTz00mCD3UGPQ6IWiO5mruJOXERhu9vjNhWFEjzK9_P-1w1pJjbwxI7Z8UYSKtB_n32nTsAQs0ETV-hOm3fRF08TXCetFDeeF0QTX4htZZR1xOAEGgMFZlR2rHCyZ7DiNnBN1PsAUkvTqF-AIzHS9RYYMLB-9laT003__m00
```
despite the above configs Telmetry logs are still being emitted to telemetry file sink. Verified using `cat cockroach-data/logs/cockroach-telemetry.log` 
```
I250625 15:44:45.497573 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 217 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":47,"Qps":0,"LeaseholderNodeID":1}
I250625 15:44:46.497940 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 218 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":33,"Qps":0,"LeaseholderNodeID":2}
I250625 15:44:47.498956 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 219 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":39,"Qps":0,"LeaseholderNodeID":1}
I250625 15:44:48.499344 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 220 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":25,"Qps":0,"LeaseholderNodeID":2}
I250625 15:44:49.499600 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 221 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":12,"Qps":0,"LeaseholderNodeID":1}
I250625 15:44:50.500660 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 222 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":51,"Qps":0,"LeaseholderNodeID":2,"WritesPerSecond":0.2691935409450028,"CPUTimePerSecond":26379.262747999725}
I250625 15:44:51.501727 2323 12@util/log/event_log.go:39 ⋮ [T1,Vsystem,n1] 223 ={"Timestamp":1750866236465283273,"EventType":"hot_ranges_stats","RangeID":28,"Qps":0,"LeaseholderNodeID":3}
```
What did you do? Describe in your own words.

**Expected behavior**
Expect excluding telemetry channel from log config, telemetry file logs would no longer be emitted, and thus save IO.

**Additional data / screenshots**
slack [thread](https://cockroachlabs.slack.com/archives/C063CP41TG9/p1750873016411979?thread_ts=1749245116.395959&cid=C063CP41TG9) 

**Environment:**
 - CockroachDB version v24.3.13
 - Server OS: K8

**Additional context**
The impact is telemetry logs consuming IO but doesn't benefit self-hosted customers.

Jira issue: CRDB-51845

**Comment by lin-crl** [comment]
The issue was found on v24.3.13. Not sure about its impact on other branches.

**Comment by dhartunian** [comment]
I cannot reproduce this: https://www.loom.com/share/a6a5b06ad6ff4006b496743557fbd903

**Comment by lin-crl** [comment]
thanks for sharing the video. I switched to cockroach start-single-node for easier testing.

Withe the following configs, TELEMETRY are emitted to default file groups

```
jessielin@mac ~ % cat log-config.yaml
      file-defaults:
        max-file-size: 10MiB
        max-group-size: 800MiB
        file-permissions: 644
        buffered-writes: false
        buffering:
          max-staleness: 1s
          flush-trigger-size: 256KiB
          max-buffer-size: 50MiB
        filter: INFO
        format: crdb-v2
        redact: false
        redactable: true
        exit-on-error: true
        auditable: false
      sinks:
        file-groups:
          default:
            channels:
              INFO: [DEV, OPS]
              WARNING: all except [DEV, OPS]
          health:
            channels: [HEALTH]
          kv-distribution:
            channels: [KV_DISTRIBUTION]
          pebble:
            channels: [STORAGE]
          security:
            channels: [PRIVILEGES, USER_ADMIN]
          sql-audit:
            channels: [SENSITIVE_ACCESS]
          sql-auth:
            channels: [SESSIONS]
          sql-exec:
            channels: [SQL_EXEC]
          sql-slow:
            channels: [SQL_PERF]
          sql-slow-internal-only:
            channels: [SQL_INTERNAL_PERF]            
        stderr:
          channels: all
          filter: NONE
          redact: false
          redactable: true
          exit-on-error: true
      capture-stray-errors:
        enable: true
        max-group-size: 500MiB
```

using cockroach debug we can see TELEMETRY would be emitted for WARNING+ in default group.
IF telemetry doesn't have WARNING+ logs, that would be one way to kind of disable it.
```
jessielin@mac ~ % cockroach debug check-log-config --log-config-file log-config.yaml
# configuration after validation:
file-defaults:
  dir: /Users/jessielin/cockroach-data/logs
  max-file-size: 10MiB
  max-group-size: 800MiB
  file-permissions: "0644"
  buffered-writes: false
  filter: INFO
  format: crdb-v2
  redact: false
  redactable: true
  exit-on-error: true
  auditable: false
  buffering:
    max-staleness: 1s
    flush-trigger-size: 256KiB
    max-buffer-size: 50MiB
    format: newline
fluent-defaults:
  filter: INFO
  format: json-fluent-compact
  redact: false
  redactable: true
  exit-on-error: false
  auditable: false
  buffering:
    max-staleness: 5s
    flush-trigger-size: 1.0MiB
    max-buffer-size: 50MiB
    format: newline
http-defaults:
  method: POST
  unsafe-tls: false
  timeout: 2s
  disable-keep-alives: false
  compression: gzip
  filter: INFO
  format: json-compact
  redact: false
  redactable: true
  exit-on-error: false
  auditable: false
  buffering:
    max-staleness: 5s
    flush-trigger-size: 1.0MiB
    max-buffer-size: 50MiB
    format: newline
sinks:
  file-groups:
    default:
      channels: {INFO: [DEV, OPS], WARNING: [HEALTH, STORAGE, SESSIONS, SQL_SCHEMA, USER_ADMIN, PRIVILEGES, SENSITIVE_ACCESS, SQL_EXEC, SQL_PERF, SQL_INTERNAL_PERF, TELEMETRY, KV_DISTRIBUTION]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    health:
      channels: {INFO: [HEALTH]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    kv-distribution:
      channels: {INFO: [KV_DISTRIBUTION]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    pebble:
      channels: {INFO: [STORAGE]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    security:
      channels: {INFO: [USER_ADMIN, PRIVILEGES]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-audit:
      channels: {INFO: [SENSITIVE_ACCESS]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-auth:
      channels: {INFO: [SESSIONS]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-exec:
      channels: {INFO: [SQL_EXEC]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-slow:
      channels: {INFO: [SQL_PERF]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
    sql-slow-internal-only:
      channels: {INFO: [SQL_INTERNAL_PERF]}
      dir: /Users/jessielin/cockroach-data/logs
      max-file-size: 10MiB
      max-group-size: 800MiB
      file-permissions: "0644"
      buffered-writes: false
      filter: INFO
      format: crdb-v2
      redact: false
      redactable: true
      exit-on-error: true
      buffering:
        max-staleness: 1s
        flush-trigger-size: 256KiB
        max-buffer-size: 50MiB
        format: none
  stderr:
    filter: NONE
    format: crdb-v2-tty
    redact: false
    redactable: true
    exit-on-error: true
    buffering:
      max-staleness: 1s
      flush-trigger-size: 256KiB
      max-buffer-size: 50MiB
      format: newline
capture-stray-errors:
  enable: true
  dir: /Users/jessielin/cockroach-data/logs
  max-group-size: 500MiB

# graphical diagram URL:
http://www.plantuml.com/plantuml/uml/X5PTRzey5Bu_lyBYwdqlCd3u2FHYAWElZKQ1aPHjqYGK4jDcJUFMThfLK__x59k4EM1sbVDyMCt9ENxAfP0HbyLZ1XdTIIGPukdTlKH9ocaiKvP3p1wVM4vpYGGhU4m5-Wt__O-cP5q-5ikWV5oJyIoyBgiWNAp6LqIL90ZynLmPWi-pJJ2v9ZVZ4jq6PBKPJs_yUOcMAt_jpyWLqKuo3_pGNvFDU38XGNsQV2MJgbwIrSUgzkSXMSt71p8aCt93mjMt4dnQRwP-4Axy3xUXlvX3dB4YGKBow1L50hLKzJsdd3CkMl06pmKjA18oePn37F44FMqsM7btZ3z6yYBcoTPvSLkrwcerpIJb5ryEVDV2zonyty8FBBnduOSMVcJXSSScO9jWQndRUiQzivyGzy_BW_EoTruUdfT7vwVREI__OpVSatB4PRgBOebsQQPk5DgnBA4SjTgtWdBH_a65I6cMvksOnG-SHV6zaqGoQcViJhJA0-eeska_NvlUPUokLOkkAJhtDCfamzDjU1vUd2GLagVRehp_fhdNC3_HxJQZfgVVy0WQ5poLhwPhq7GzPqvK9AaqRTv9MxE7uGaN_KLZqpKwuH8P-scwzhVXsEQakQGyZpA7vPdPZOuBLJREAc7lVOCtc98rSfptQkzWiGmEG4TeXLtO1sb5TA6AquhfmI5KAwuFXsYjk04S0hRYF6Z6RAKCeGhRYXb15RdrotRWA7bh3KCTm3NdGYE7QwKBAbvBkCEWmhJ-8Yf2_qOz0_KDD32GPw2XWKO6mXqJOXEQhuExjddX7kYKKvtO--s3JZjbwpQ7Z0UWqqx9lHF3nDw9QM8FT0ggOtthRF4GT1mgt-1ee_08T1ugtJlQ1BS3EX2LFZpQ2rTFS3_EaNr9N1TqDkgvTq3_GoxHuIh19SsJyfV9dm000F__

```
