### ISSUE TITLE
storage: re-enable Raft PreVote RPC

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16950]
Enable the Raft PreVote feature. Note, the implementation of Raft PreVote exists, but stability issues arose when it was turned on. This task is about fixing those issues (if they still exist).

Raft PreVote is a mechanism to lessen the impact of a rogue replica calling a Raft election. When a replica calls a Raft election it forces the current leader to step down and we have to wait for the election to complete. This disrupts activity on the affected Range. A replica might call an election mistakenly if it was partitioned away temporarily. The unfortunate part about it calling an election when it rejoins the cluster is that it can't possibly succeed because it is not up to date. Raft PreVote is a mechanism for a replica to check whether other replicas would vote for it if it held an election. 

Archaeology: we don't really know why it wasn't working, and simply disabled it.

```
commit 1d59f01c9b3523f31d8415ecbd1096d0b51fbbc6
Author: Tamir Duberstein <tamird@gmail.com>
Date:   Thu Nov 3 12:05:59 2016 -0400

    GLOCKFILE: update dependencies
    
    Summary of not-definitely-irrelevant changes:
    - github.com/cenkalti/backoff:
      - moved from github.com/cenk/backoff: https://github.com/cenkalti/backoff/commit/b02f2bb
    - github.com/cockroachdb/c-protobuf:
      - updated upstream to 3.1.0: https://github.com/cockroachdb/c-protobuf/pull/20
    - github.com/gogo/protobuf:
      - rename generated variables data->dAtA: https://github.com/gogo/protobuf/pull/215
    - github.com/etcd/raft:
      - PreVote-related panic fix: https://github.com/coreos/etcd/pull/6749
    - github.com/lib/pq:
      - data race fix: https://github.com/lib/pq/commit/473284b
    
    Not reviewed in detail:
    - github.com/go-sql-driver/mysql
    - github.com/google/go-github
    - golang.org/x/crypto
    - golang.org/x/net
    - golang.org/x/oauth2
    - golang.org/x/sys
    - golang.org/x/text
    - golang.org/x/tools
    - google.golang.org/appengine
    
    Skipped:
    
    - github.com/cockroachdb/c-rocksdb (#9616)
    - github.com/docker/docker (https://github.com/docker/docker/pull/27912) breaks all dependents
    - google.golang.org/grpc (#9697)

commit 9ce883365db916baa8a6d66d16bc153e7b3977e0
Merge: 99e14f718 f61b94d05
Author: Alex Robinson <alexdwanerobinson@gmail.com>
Date:   Wed Nov 2 12:10:33 2016 -0400

    Merge pull request #10395 from bdarnell/bdarnell/disable-prevote
    
    storage: Switch back from PreVote to CheckQuorum

commit f61b94d05fa83ec31885281c19d89fb97b5d796f
Author: Ben Darnell <ben@cockroachlabs.com>
Date:   Wed Nov 2 22:41:06 2016 +0800

    storage: Switch back from PreVote to CheckQuorum
    
    PreVote has bugs that show up under chaos testing.

commit b0bb16e39a762ab49b0c87308829548be0238c24
Merge: 791502496 601cb79aa
Author: Ben Darnell <ben@bendarnell.com>
Date:   Wed Nov 2 19:42:01 2016 +0800

    Merge pull request #10218 from bdarnell/prevote
    
    storage: Use raft PreVote instead of CheckQuorum

commit 601cb79aa65b9eebd2f142b1c64b753ce995b3be
Author: Ben Darnell <ben@cockroachlabs.com>
Date:   Wed Oct 26 08:46:00 2016 +0900

    storage: Stop calling raftGroup.TickQuiesced
    
    This was a workaround for the interaction between quiesced ranges and
    CheckQuorum, and is no longer needed now that we have switched from
    CheckQuorum to PreVote.
    
    Reverts #9407

commit 65963433dea55bee2b9e707d1497f97838df700c
Author: Ben Darnell <ben@cockroachlabs.com>
Date:   Wed Oct 19 11:07:32 2016 +0800

    storage: Use raft PreVote instead of CheckQuorum
    
    CheckQuorum interacts badly with quiesced ranges and coalesced
    heartbeats; the new PreVote implementation provides the same benefits in
    a way that is more compatible with our use.
    
    Fixes #9561
```
