### ISSUE TITLE
CockroachDB v1.0 write performance is half as fast as postgreSQL?

### ISSUE THREAD

**Issue by Spazer9** [cockroachdb/cockroach#17777]
I'd like to congratulate the people working on this project (It's awesome) - i was looking for a distributed SQL db with strong consistency and cockroachDB seems like the best proposal out there.

I'm not a DB guru by any stretch but I really wanted to see the baseline performance difference between PostgreSQL and Cockroach on a single node just out of curiosity. I made a makeshift NodeJS benchmark script that inserts 2000 records into a table it creates (which has 3 indexes), then tries to benchmark a few selects using one of the indexes.

Here's the schema i used:

```
CREATE TABLE customers_bench (
    id SERIAL NOT NULL,
    first_name varchar(250) DEFAULT NULL,
    last_name varchar(250) DEFAULT NULL,
    email varchar(250) DEFAULT NULL,
    age INT DEFAULT NULL,
    PRIMARY KEY (id)
  );
CREATE INDEX ON customers_bench (email);
CREATE INDEX ON customers_bench (age);
```

It looked like Postgresql inserts 2k records in 3.8s while cockroach does it in 7.3s.

Postgresql:

![](https://s3.amazonaws.com/snaps-bucket/2017/08/g52ZKzs/2017-08-21_09-22-58.png)

Cockroach DB:

![](https://s3.amazonaws.com/snaps-bucket/2017/08/QItr26s/2017-08-21_09-23-47.png)

Selecting by an index takes exactly the same time between Postgersql & Cockroach (~2ms to select by an index).

## How to replicate:

I've used a `t2.small` for both the cockroach EC2 server and the postgresql RDS server on AWS. I have done 0 extra configuration/tweaks on both. 

## How to benchmark:

Get my Node js script from here: https://gist.github.com/Spazer9/a6073cdc58d103bf5ac055be28589114

Make sure you got Node 7.6 and up. install the `pg` package. then run:

`node sql_bench.js --host=XXXXX --port=XXXX --user=XXXX --pw=XXX --db=XXXX`

This will work on both postgresql and cockroach dbs.

**Comment by petermattis** [comment]
PostgreSQL is usually faster than single-node CockroachDB at this time. We'll narrow that gap over time, but the real advantage to Cockroach is the easy horizontal scalability without having to resort to sharding.

Looking at your code, one thing to be aware of is that Cockroach is more sensitive to roundtrips to the server than a traditional single-node database. You want to minimize those roundtrips. Inserting 1 row at a time is sometimes needed for OLTP workloads, but if you're trying to bulk insert data, see [the FAQ](https://www.cockroachlabs.com/docs/stable/sql-faqs.html#how-do-i-bulk-insert-data-into-cockroachdb). Batching hundreds or thousands of rows into a single `INSERT` statement will be orders of magnitude faster for both PostgreSQL and CockroachDB.

**Comment by amq** [comment]
I wish I could achive your results... When testing with `sysbench 1.1` against Galera, both single-nodes, I get:

`oltp_write_only`
cockroach
transactions: 34.19 per sec.
queries: 205.15 per sec.

galera
transactions: 870.68 per sec.
queries: 5224.08 per sec.

`oltp_read_only`
cockroach
transactions: 106.54 per sec.
queries: 1704.58 per sec.

galera
transactions: 449.72 per sec.
queries: 7195.46 per sec.

***

Clients (threads): 1
Tables: 4
Table rows: 250k
RAM: 4G, 25% for both caches
CPUs: 4

If this is of interest, I can open a separate issue with all details.

**Comment by petermattis** [comment]
@amq Can you provide the exact `sysbench` command line you ran against Cockroach? I haven't done any significant investigation into `sysbench`, but the numbers you posted seem low.

**Comment by amq** [comment]
@petermattis 

```
sysbench --db-driver=pgsql --pgsql-host=cockroachdb-01 --pgsql-port=26257 --pgsql-user=root oltp_read_only --tables=4 --table-size=250000 prepare
sysbench --db-driver=pgsql --pgsql-host=cockroachdb-01 --pgsql-port=26257 --pgsql-user=root oltp_read_only --time=60 --threads=1 run
```

Some other tests:

```
oltp_write_only
oltp_read_write
oltp_update_non_index
```

Make sure to run the master (1.1) of sysbench if you want to try more threads than one. See https://github.com/akopytov/sysbench/commit/0169d42681ab699a05533a1e9294e98ab6494535

My docker-compose.yml:

```
version: "3.1"

services:
  cockroachdb-01:
    hostname: cockroachdb-01
    image: cockroachdb/cockroach:${COCKROACHDB_VERSION:-v1.1.2}
    command: |-
      start
      --join=cockroachdb-01:26257
      --cache=25%
      --max-sql-memory=25%
      --logtostderr
      --insecure
    ports:
      - "8080:8080"
      - "26257:26257"
    volumes:
      - cockroachdb-01:/cockroach/cockroach-data
    networks:
      - mynet
    deploy:
      placement:
        constraints:
          - node.hostname == ${BASE_HOSTNAME:-node}-01

volumes:
  cockroachdb-01:

networks:
  mynet:
    external: true
```
