### ISSUE TITLE
ERROR: cockroach server exited with error: failed to start store: [n1,s1]: cannot addReplicaInternalLocked

### ISSUE THREAD

**Issue by yiv** [cockroachdb/cockroach#18577]
```
ERROR: cockroach server exited with error: failed to start store: [n1,s1]: cannot addReplicaInternalLocked; range [n1,s1,r325/1:/System/tsd/cr.node.sql.mem.c…] has overlapping range r20540:/System/tsd/cr.node.sql.mem.client.max-p99.9/{1/10s/2017-08-17T23:00:00Z-3/10s/2017-08-17T23:00:00Z} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4]
```
I deployed cockroachdb sine v1.0.1, and this happened after i upgraded from v1.0.4 to v1.0.5, this didn't happen when i restart after upgraded, it happened days later after I have done upgrade when the concurrency growing, 

I use docker-compose to deploy 3 nodes of cockroachdb 
```
version: '3'
services:
  cockroach1:
    image: cockroachdb/cockroach:v1.0.5
    hostname: cockroach1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - /data/docker/data/cockroach/roach1:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - cocknetwork
    restart: always
  cockroach2:
    image: cockroachdb/cockroach:v1.0.5
    hostname: cockroach2
    volumes:
      - /data/docker/data/cockroach/roach2:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always
  cockroach3:
    image: cockroachdb/cockroach:v1.0.5
    hostname: cockroach3
    volumes:
      - /data/docker/data/cockroach/roach3:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always 
networks:
  cocknetwork:
    driver: bridge
```
The error just happened on cockroach1
