### ISSUE TITLE
docker: Create default database

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#19826]
The docker images for postgres and mysql support environment variables (POSTGRES_DB and MYSQL_DATABASE) that will cause a default database to be created (among other things; looks like a user can be created too). We may want to allow similar automatic configuration for use in testing. 

Epic CRDB-1424

**Comment by Rio** [comment]
As I see it, it is usually done through some bash scripts that get run as part of the ENTRYPOINT in docker.
Looks like `/cockroachdb/cockroach.sh` is a good place to set it up. Not sure how it works in clustered mode though.

Mysql does some sort of double boot of mysql, starts it in the background, does the setup magic against that instance, stops it, and starts the real thing.

**Comment by jhayotte** [comment]
I add my workaround to define a COCKROACH_DB at startup in a docker-compose:

```
article_cockroachdb:
    image: mycorp/cockroach
    command: start --insecure
    ports:
      - "8080"
      - "26257"
    restart: unless-stopped

  article-cockroachdb-init:
    image: mycorp/cockroach
    entrypoint: /cockroach/init.sh 
    command: article
    depends_on:
      - article_cockroachdb
    restart: on-failure
```
My init.sh:
```
#!/bin/sh

host=$1_cockroachdb

./cockroach sql --insecure --host="$host" --execute="  DROP USER IF EXISTS cockroach; \
                                        DROP DATABASE IF EXISTS $1 CASCADE; \
                                        CREATE DATABASE IF NOT EXISTS $1; \
                                        CREATE USER cockroach WITH PASSWORD 'password'; \
                                        GRANT ALL ON DATABASE $1 TO cockroach;"
```

Either you create your own Docker image with this init.sh or you mount a volume in `article-cockroachdb-init`.

Hope it will help.

**Comment by knz** [comment]
cc @dianasaur323 for prioritization

**Comment by dianasaur323** [comment]
since this is docker, let's have @kannanlakshmi take a look

**Comment by a-robinson** [comment]
We could make this sort of thing work for the single-node case, but it can't really work for the multi-node case given the inability to create DB/users on an uninitialized cluster.

To the folks that are commenting/upvoting this:

1. Do you still want this or have you all worked around it by now?
2. Are you all using insecure mode?
3. Are you all using a single-node deployment or at least not using `cockroach init`?
4. Do you want control over anything more than a database, user, and password?

**Comment by knz** [comment]
Note that we're also shipping #24735 in 2.1 which will provide two predefined dbs in all cases. Maybe this will also help?

**Comment by jhayotte** [comment]
@knz Your pull request will definitely help! Thx for it!
Just one thing, IMHO you don't cover one important use case: 

**As a developer I want to run my test of integration in a specific cockroach DB with a docker_compose.**

In this scenario, you need to define in your docker-compose a COCKROACH_DB (e.g article)

As mention earlier, this use case occurs when you run a single instance of crdb. When you run your test locally, this is the case :)

**Comment by saward** [comment]
Not exactly this issue, but I couldn't find a way to initialise cockroach easily with arbitrary SQL commands for purposes of testing.  I therefore created a simple script that will run the set of SQL files contained within a specified folder.  You can use this to create databases as well as initialise that database with whatever structure and data you wish (source code on github as linked from repo):

https://hub.docker.com/r/episub/cockroach-init/

If there already exists a way to do this, please let me know.

**Comment by inieves** [comment]
The solutions I see here are correct, but they seem heavyweight to me.  I also see Docker being used in some heavyweight ways to work around challenges that are created by various images.

In the case of cockroach, I have the same issue... I want to run an init script immediately after db creation.  Yes, I realize that in true cluster mode (>1 node) this does not make sense.

I would argue that the developer should be able to init a db or a cluster of db nodes, using the same script or function call.  The implementation may change (depending on if single node or multi-node), but the idea remains the same.. The developer needs the db/cluster to have a particular state immediately after creation.  This is so clearly necessary, the cockroach start command should have a command line flag to specify a shell script to execute or perhaps an SQL command to execute.

Anyways... here is a somewhat simpler solution requiring only docker-compose:

db_cockroach:
    ......
    command: shell -c '/etc/cockroach/conf/init-user-db.sh & /cockroach/cockroach start --certs-dir=/etc/cockroach/certs;'

You simply fork (using "&") your init script before you launch cockroach... BUT, you must make sure you init script is efficiently polling the port that cockroach will be listening on when it wakes up...  so that when cockroach actually wakes up, your init script can run.

I made use of the "nc" program a.k.a. netcat to poll... and my solution (init-user-db.sh) looks like:

============
#!/bin/bash
set -e
while ! nc -w 1 -z localhost 26257; do sleep 0.1; done;
/cockroach/cockroach sql --certs-dir=/etc/cockroach/certs --user=root --execute="
	CREATE USER IF NOT EXISTS $COCKROACH_USER;
	CREATE DATABASE IF NOT EXISTS $COCKROACH_DATABASE;
	GRANT CREATE, SELECT, DROP, INSERT, DELETE, UPDATE ON DATABASE $COCKROACH_DATABASE TO $COCKROACH_USER;
"
============

notice nc is used in a loop, whereby it checks to see if any process is listening on the cockroach port, then sleeps for 1/10 of a second.

This solution does not require any new Docker containers to be created... it basically adds one line to your init script, requires you to apt-get install netcat, and adds a little more muck to your docker-compose command.

In my final analysis, to bring cockroach up to speed with mysql/maria/postgres, it should support the ability to create an initial non-root user and an initial database (both with the name of the users choosing).  It should also allow the user to supply an init script.  There is a best practice for doing this in Docker... see what mysql/maria/postgres did.  cockroach could also address the issue for non-Docker situations by allowing the user to supply cockroach start with a command line flag that specifies an init shell script or SQL script.  All this can be done in a way that achieves the developers intended result regardless of single-node or multi-node.

**Comment by StephenGrider** [comment]
Kubernetes solution here.

This job will initialize a cluster + run an init script against the cluster.  Note that this assumes a secret `cr-db-secret` with a comma-separated list of DB's to create, in addition to CR_USER and CR_PASSWORD variables.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-init-secure
  labels:
    app: cockroachdb
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 3600
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: cockroachdb
      initContainers:
        - name: init-certs
          image: cockroachdb/cockroach-k8s-request-cert:0.4
          imagePullPolicy: IfNotPresent
          command:
            - '/bin/ash'
            - '-ecx'
            - '/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client -user=root -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach-certs
      restartPolicy: OnFailure
      volumes:
        - name: client-certs
          emptyDir: {}
      containers:
        - name: cluster-init
          image: cockroachdb/cockroach:v2.1.4
          imagePullPolicy: Always
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach-certs
          env:
            - name: CR_DBS
              value: accounts,classes,discussions,exercises,votes,workspaces
            - name: CR_USER
              valueFrom:
                secretKeyRef:
                  key: CR_USER
                  name: cr-db-secret
            - name: CR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: CR_PASSWORD
                  name: cr-db-secret
          command: 
            - /bin/sh
            - -c
            - |
              {
                echo "Initializing cluster..."
                while ! /cockroach/cockroach init --certs-dir=/cockroach-certs --host=cockroachdb-0.cockroachdb 2>&1 >/dev/null | grep AlreadyExists; do sleep 1; done;
              } && {
                echo "Creating user"
                /cockroach/cockroach sql --user=root --certs-dir=/cockroach-certs --host=cockroachdb-0.cockroachdb --execute="
                  CREATE USER IF NOT EXISTS $CR_USER WITH PASSWORD $CR_PASSWORD;
                "

                echo "Initializing databases..."
                for db in $(echo $CR_DBS | sed "s/,/ /g")
                do
                  /cockroach/cockroach sql --user=root --certs-dir=/cockroach-certs --host=cockroachdb-0.cockroachdb --execute="
                    CREATE DATABASE IF NOT EXISTS $db;
                    GRANT CREATE ON DATABASE $db TO $CR_USER;
                  "
                  echo Created db $db
                done
              }

```          
      
Sample `cr-db-secret` secret:
```
kubectl create secret generic cr-db-secret \
  --from-literal=CR_USER=devuser \
  --from-literal=CR_PASSWORD=devpassword
```
