### ISSUE TITLE
Nodes keep getting into suspect state

### ISSUE THREAD

**Issue by matjazmav** [cockroachdb/cockroach#24402]
Hey, I have problem that nodes keep jumping from healthy to suspect state. All nodes are running on single machine and are started with docker-compose.

I went through production checklist and set Google NTP service. But since this is single machine deployment this shouldn't effect CRDB. Please correct me if I'm wrong. Maybe this result of my slow internet connection today, but again I'm running this cluster on single machine in LAN.

```
$ sudo ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
+time1.google.co .GOOG.           1 u   56   64  377  129.453   -3.770   1.977
-time2.google.co .GOOG.           1 u   65   64  377  139.320   -2.928   2.391
*time3.google.co .GOOG.           1 u   63   64  377   37.503   -5.607   2.782
+time4.google.co .GOOG.           1 u   52   64  377  138.637   -6.425   3.281
```

![image](https://user-images.githubusercontent.com/9011654/38190120-20fc956a-3663-11e8-9bb4-2a8d97251d59.png)

**docker-compose.yml:**
```
version: '3.4'

services:
  roach0:
    image: cockroachdb/cockroach
    ports:
      - 8080
    command: 'start --insecure --join=roach0,roach1,roach2 --cache=25% --max-sql-memory=25%'

  roach1:
    image: cockroachdb/cockroach
    command: 'start --insecure --join=roach0,roach1,roach2 --cache=25% --max-sql-memory=25%'

  roach2:
    image: cockroachdb/cockroach
    command: 'start --insecure --join=roach0,roach1,roach2 --cache=25% --max-sql-memory=25%'

  proxy:
    image: haproxy
    ports:
      - 26257
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
```

**How I'm starting CRDB**
```
$ docker-compose up -d
$ docker exec cockroachdb_roach0_1 /cockroach/cockroach init --insecure --host roach0
```

**Comment by petermattis** [comment]
@matjazmav Thanks for the report. What version of Cockroach are you running? From the screenshot it appears to be a 1.1.x release.

I'm sure you're aware, but running 3 nodes on a single machine defeats the durability of writes to a Cockroach system, while at the same time causing lower performance. I hope this is only being done for testing. One thing I noticed about your config is that  you've specified `--cache=25%` and `--max-sql-memory=25%` for each of these nodes. `25*2*3 == 150`. I doubt that is the cause of the suspect nodes, but you should probably fix it. Setting those flags to `5%` or `10%` should be fine for testing.

Can you send along the debug log files? These are stored in `cockroach-data/logs` on each of the nodes.

**Comment by a-robinson** [comment]
There are a couple possible reasons for this depending on where your docker host is running:

* https://github.com/cockroachdb/cockroach/pull/22237 fixed a bug in v1.1 where nodes could be listed as suspect if there was a clock difference between your web browser and the nodes in the cluster. This could be happening if your Docker host is on a VM somewhere and you're viewing the admin UI on your local machine.
* If your local machine is a mac and you're running docker locally, there's a known issue with the VM used by docker for mac getting out of sync with the mac's clock (https://github.com/docker/for-mac/issues/2076). When combined with the above bug in v1.1, it would make all the nodes look suspect.

Could either of these be what's going on? Both would be fixed by using a v2.0 beta or release candidate.

**Comment by matjazmav** [comment]
@petermattis Yes it it 1.1.7 release. I'll share log files tomorrow when I get back to PC.

@a-robinson I already tried with the same stack file only using cockroachdb/cockroach-unstable image, got same results.

**Some more info:**
I had problem (still have) with slow SQL latency. I used loadgen-ycsb and latency went up over 6 seconds. Then I slowly started to remove possible problematical parts and eventually ended with compose file. After that I also tested single CRDB and it looked much better. With loadget-ycsb I was able to between 700 to 900 operations per second with 99 percentile SQL latency around 200ms.

mav-ubuntu-02: i7 8 cores, 4GB ram, HDD, gigabit etherent (full duplex)
mav-ubuntu-01: i5 4 cores, 4GB ram, HDD, gigabit etherent (full duplex)
mav-ubuntu-03: i5 4 cores, 4GB ram, HDD, fast etherent (full duplex)
** All nodes are running Ubuntu Server 16.04.4 LTS, Docker CE 18.03.0-ce and using Google NTP service

**cockroachdb-stack.yml**
```
version: '3.4'

configs:
  haproxy_config:
    file: ./haproxy.cfg

services:
  roach0:
    image: cockroachdb/cockroach
    volumes:
      - /data/volumes/cockroachdb/roach0:/cockroach/cockroach-data
    command: 'start --insecure --join=roach0,roach1,roach2'
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-02

  roach1:
    image: cockroachdb/cockroach
    volumes:
      - /data/volumes/cockroachdb/roach1:/cockroach/cockroach-data
    command: 'start --insecure --join=roach0,roach1,roach2'
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-01

  roach2:
    image: cockroachdb/cockroach
    volumes:
      - /data/volumes/cockroachdb/roach2:/cockroach/cockroach-data
    command: 'start --insecure --join=roach0,roach1,roach2'
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-03

  proxy:
    image: haproxy
    ports:
      - 26257
      - 8080
    configs:
      - source: haproxy_config
        target: /usr/local/etc/haproxy/haproxy.cfg
    deploy:
      placement:
        constraints:
          - node.hostname == mav-ubuntu-02
```
** `/data/volume/cockroachdb/*` is NFS mounted folder
