### ISSUE TITLE
monitoring: wrong setting of path_prefix for  Alertmanager

### ISSUE THREAD

**Issue by yaojingguo** [cockroachdb/cockroach#27821]
I followed [Monitor CockroachDB with Prometheus](https://cockroachlabs.com/docs//v2.0/monitor-cockroachdb-with-prometheus.html) to set up  Alertmanager. When Prometheus sended an alter to Alertmanager, there was the following error:

```
level=error ts=2018-07-21T08:14:57.875737602Z caller=notifier.go:473 component=notifier alertmanager=http://localhost:9093/alertmanager/api/v1/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"
```

Updating `path_prefix` to `"/"` in `monitoring/prometheus.yml` fixed the problem.

```
# Alert manager running on the same host:
alerting:
  alertmanagers:
  - path_prefix: "/alertmanager/"
    static_configs:
    - targets:
      - localhost:9093
```

The following is version information for Prometheus and Alertmanager:
```
prometheus, version 2.3.2 (branch: HEAD, revision: 71af5e29e815795e9dd14742ee7725682fa14b7b)
  build user:       root@5258e0bd9cc1
  build date:       20180712-14:08:00
  go version:       go1.10.3

alertmanager, version 0.15.1 (branch: HEAD, revision: 8397de1830f154535a31150f9262da0072d8725d)
  build user:       root@efde7f9485ae
  build date:       20180712-18:26:48
  go version:       go1.10.3
```
