### ISSUE TITLE
Trouble using a separate client CA in Kubernetes

### ISSUE THREAD

**Issue by glerchundi** [cockroachdb/cockroach#30188]
Is this a bug report or a feature request?

Bug report.

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?

`cockroachdb/cockroach-unstable:v2.1.0-beta.20180910`

- What did you do?

Add (mount) `ca-client.crt` from a freshly created `ConfigMap` in a Kubernetes CockroachDB deployment:

ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cockroachdb
  namespace: database-system
  labels:
    app: cockroachdb
data:
  ca-client.crt: |
    -----BEGIN CERTIFICATE-----
[...]
```

Part of the `StatefulSet`:
```
[...]
        - name: certs
          mountPath: /cockroach/cockroach-certs
        - name: certs-ca-client
          mountPath: /cockroach/cockroach-certs/ca-client.crt
          subPath: ca-client.crt
[...]
      - name: certs-ca-client
        configMap:
          name: cockroachdb
[...]
```

- What did you expect to see?

Everything to be upgraded without issues.

- What did you see instead?

Cluster get stuck in this state. If I destroy the running pod another way gets created for the first time but no other node gets connected to the cluster.

```
$ kubectl get pods
NAME                 READY     STATUS    RESTARTS   AGE
cockroachdb-0        0/1       Running   0          4m
cockroachdb-1        0/1       Running   0          23m
cockroachdb-2        1/1       Running   0          41m
```

A lot of these logs were present:
```
W180913 11:31:02.521971 134 storage/node_liveness.go:558  [n1,hb] slow heartbeat took 4.5s
W180913 11:31:02.522345 134 storage/node_liveness.go:494  [n1,hb] failed node liveness heartbeat: context deadline exceeded
W180913 11:31:07.023070 134 storage/node_liveness.go:558  [n1,hb] slow heartbeat took 4.5s
W180913 11:31:07.023440 134 storage/node_liveness.go:494  [n1,hb] failed node liveness heartbeat: context deadline exceeded
```

- What was the impact?

Cluster down.

- Comments

Running on GKE so this seems weird because I don't think there is an issue with networking speed. 

Things get even worse when I tried to upgrade the k8s cluster thinking that the problem was related to the VM speed or whatever related to the machine (disk io, networking, cpu, ...) because the cluster didn't proceed the upgrading progress presumibly due to cockroachdb's pod disruption budget of maxUnavailable = 1 (cluster was with more than one unavailable).

/cc @asubiotto @a-robinson
