### ISSUE TITLE
Error while running cockroach dump

### ISSUE THREAD

**Issue by ernanieg** [cockroachdb/cockroach#30230]
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
cockroachdb/cockroach:v2.0.5

- What did you do?
run ./cockroach dump bank --url=postgres://root@cockroachdb-public:26257/bank?sslmode=disable

- What did you expect to see?
Successful back up of cockroach dump

- What did you see instead?
Error: getBasicMetadata: relation bank.public.&gt; does not exist
Failed running "dump"

- What was the impact?
Major

This was executed at a kubernetes pod using this yaml file
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cockroachdb-dump
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cockroachdb-dump
            image: cockroachdb/cockroach:v2.0.5
            args:
            - "dump"
            - "bank"
            - "--url=postgres://root@cockroachdb-public:26257/bank?sslmode=disable"
            - "--insecure"
            - ">"
            - "backup.sql"
          restartPolicy: OnFailure
```
