### ISSUE TITLE
server,ui: CPU count metric is incorrect when using containers/orchestration/k8s

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#34988]
**Describe the problem**

using Kubernetes on a server with 64 virtual CPUs and resource limits as below

```
resources:
  limits:
    cpu: "4"
    memory: 8Gi
  requests:
    cpu: "4"
    memory: 8Gi
```

Admin UI reports 64 CPUs instead of 4 CPUs.

**To Reproduce**

Using 
CockroachDB 2.1.4
Kubernets 1.13.2

**Expected behavior**

is this expected behavior?
