### ISSUE TITLE
Index selection does make unfortunate decisions since version 2.1.0

### ISSUE THREAD

**Issue by Dobiasd** [cockroachdb/cockroach#35451]
The table layout for the minimal example to reproduce the problem is:
```
"CREATE TABLE my_table (
    id INT NOT NULL,
    value INT NOT NULL,
    name STRING NULL,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    INDEX value_idx (value ASC),
    FAMILY "primary" (id, value, name)
)
```

The following query, filtering values with a list, uses the index `value_idx` fine up to version `2.0.6` of CockroachDB:
```
SELECT * FROM db.my_table WHERE value in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21);
```
But since version `2.1.0` this results in a linear table scan instead.

Interestingly with one value less in the list, it's still OK, i.e., also versions `>= 2.1.0` then use the index:
```
SELECT * FROM db.my_table WHERE value in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20);
```

I found out about this when updating (a 3-node cluster running on Kubernetes) from `2.0.3` to `2.1.5`. Previously fast queries suddenly timed out. The affected table had around 50M rows, so the automatic decision to not use the index in that case does not make much sense.

One possible workaround to make the DB use the index for all queries, is to use index hinting:
```
SELECT * FROM db.my_table@value_idx
```

But implementing this everywhere is quite inconvenient, especially with auto-generating queries in the attached microservices.

So I hope that this can be solved in the DB directly.

---

Here is everything needed to reproduce the issue locally:

`docker-compose.yml`:
```
version: '3'

services:

  cockroachdb.v.2.0.6:
    image: cockroachdb/cockroach:v2.0.6
    command: start --insecure --host cockroachdb.v.2.0.6

  cockroachdb.v.2.1.0:
    image: cockroachdb/cockroach:v2.1.0
    command: start --insecure --host cockroachdb.v.2.1.0

  cockroachdb.v.2.1.5:
    image: cockroachdb/cockroach:v2.1.5
    command: start --insecure --host cockroachdb.v.2.1.5

  test:
    image: cockroachdb/cockroach:v2.1.5
    depends_on:
      - cockroachdb.v.2.0.6
      - cockroachdb.v.2.1.0
      - cockroachdb.v.2.1.5
    volumes:
      - ./:/tests
    entrypoint: /tests/run_tests.sh
```

`run_tests.sh`
```bash
#!/usr/bin/env bash

declare -a hosts=("cockroachdb.v.2.0.6" "cockroachdb.v.2.1.0" "cockroachdb.v.2.1.5")

for host in "${hosts[@]}"
do
    echo ==================================
    echo USING $host

    /cockroach/cockroach sql --host=$host --insecure -e 'CREATE DATABASE db; CREATE USER usr; GRANT ALL ON DATABASE db TO usr;' > /dev/null 2>&1
    /cockroach/cockroach sql --host=$host --insecure -e 'SET DATABASE = db; CREATE TABLE my_table (id INT NOT NULL, value INT NOT NULL, name STRING NULL, CONSTRAINT "primary" PRIMARY KEY (id ASC), INDEX value_idx (value ASC));' > /dev/null 2>&1
    echo ------------------
    /cockroach/cockroach sql --host=$host --insecure -e 'EXPLAIN SELECT * FROM db.my_table WHERE value in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20);'
    echo ------------------
    /cockroach/cockroach sql --host=$host --insecure -e 'EXPLAIN SELECT * FROM db.my_table WHERE value in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21);'

done
```

When ran with
```bash
docker-compose -f docker-compose.yml up test
```

the output shows that version 2.0.6 is using the index for both queries, but version 2.1.0 (as well as 2.1.5) is ignoring it for the second query:

```
==================================
USING cockroachdb.v.2.0.6
------------------
Tree   Field   Description
index-join
" ├── scan"
" │"   table   my_table@value_idx
" │"   spans   /1-/21
" └── scan"
       table   my_table@primary
------------------
Tree   Field   Description
index-join
" ├── scan"
" │"   table   my_table@value_idx
" │"   spans   /1-/22
" └── scan"
       table   my_table@primary
==================================
USING cockroachdb.v.2.1.0
------------------
tree   field   description
index-join
" ├── scan"
" │"   table   my_table@value_idx
" │"   spans   /1-/21
" └── scan"
       table   my_table@primary
------------------
tree   field   description
scan
       table   my_table@primary
       spans   ALL
       filter  value IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)
==================================
USING cockroachdb.v.2.1.5
------------------
tree   field   description
index-join
" ├── scan"
" │"   table   my_table@value_idx
" │"   spans   /1-/21
" └── scan"
       table   my_table@primary
------------------
tree   field   description
scan
       table   my_table@primary
       spans   ALL
       filter  value IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)
```
