### ISSUE TITLE
Problem when fetching hostname using load balancer

### ISSUE THREAD

**Issue by 733amir** [cockroachdb/cockroach#39542]
**Describe the problem**

I am using Docker Swarm network aliases for a load balancer in overlay driver. I have 3 instances of CockroachDB running with the following names:

- `cockroach_1`
- `cockroach_2`
- `cockroach_3`

And an alias for all of them named `cockroach` (that will act as a load balancer).

I wanted to benchmark the cluster using `workload` subcommand but with some of the workloads, it works and with others, it won't.

**To Reproduce**

The following `cockroach.yml` file is the configuration of a 3 instance cluster of my CockroachDB:

```yaml
version: '3.7'

networks:
  cockroach:
    driver: overlay

volumes:
  cockroach_1:
  cockroach_2:
  cockroach_3:

services:
  cockroach_1:
    image: cockroachdb/cockroach:v19.1.3
    command: start --join=cockroach_1:26257,cockroach_2:26257,cockroach_3:26257 --advertise-addr=cockroach_1 --insecure
    hostname: cockroach_1
    networks:
      cockroach:
        aliases:
          - cockroach
    ports:
      - "8081:8080"
    volumes:
      - type: volume
        source: cockroach_1
        target: /cockroach/cockroach-data

  cockroach_2:
    image: cockroachdb/cockroach:v19.1.3
    command: start --join=cockroach_1:26257,cockroach_2:26257,cockroach_3:26257 --advertise-addr=cockroach_2 --insecure
    hostname: cockroach_2
    networks:
      cockroach:
        aliases:
          - cockroach
    ports:
      - "8082:8080"
    volumes:
      - type: volume
        source: cockroach_2
        target: /cockroach/cockroach-data
  
  cockroach_3:
    image: cockroachdb/cockroach:v19.1.3
    command: start --join=cockroach_1:26257,cockroach_2:26257,cockroach_3:26257 --advertise-addr=cockroach_3 --insecure
    hostname: cockroach_3
    networks:
      cockroach:
        aliases:
          - cockroach
    ports:
      - "8083:8080"
    volumes:
      - type: volume
        source: cockroach_3
        target: /cockroach/cockroach-data
```

Deploy the above configuration with the following command:
`docker stack deploy database -c cockroach.yml`

Now open interactive shell against any of the containers running CockroachDB using:
`docker exec -it CONTAINER_NAME sh`

Run the following in the container to initialize the cluster:
`./cockroach init --insecure --host=cockroach`

As you can see we initialize the cluster using the load balanced name.

Now, if you run the following in the container everything works ok and you get your results:
`./cockroach workload run bank --init --drop --duration=1m 'postgresql://root@cockroach:26257?sslmode=disable'
`

But if you only change the workload to `kv` and run the following:
`./cockroach workload run kv --init --drop --duration=1m 'postgresql://root@cockroach:26257?sslmode=disable'`
you will get the following error:
`Error: dial unix cockroach/.s.PGSQL.26257: connect: not a directory`

**Expected behavior**

I want to be able to run other workloads too.

**Additional data / screenshots**

![image](https://user-images.githubusercontent.com/8651598/62832069-439f0500-bc3e-11e9-9490-5137c42d9c9e.png)

**Environment:**

The official docker build is used as you can see in the YAML configuration.
