### ISSUE TITLE
Cockroachdb docker container permanently restarting

### ISSUE THREAD

**Issue by artem-sydorenko** [cockroachdb/cockroach#40413]
System: Windows 10
Docker: 19.03.1

docker-compose.yml
```
version: '3'

services:
  ...
  db:
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    image: cockroachdb/cockroach
    container_name: cockroachdb
    restart: on-failure
    command: start --insecure
    volumes:
      - ./docker/cockroach-data:/cockroach/cockroach-data
    networks:
      - app-network
```

The command 'docker logs --tail 50 --follow --timestamps cockroachdb' output:
```
2019-08-31T12:36:21.485302900Z * WARNING: RUNNING IN INSECURE MODE!
2019-08-31T12:36:21.485307200Z *
2019-08-31T12:36:21.485310400Z * - Your cluster is open for any client that can access <all your IP addresses>.
2019-08-31T12:36:21.485314700Z * - Any user, even root, can log in without providing a password.
2019-08-31T12:36:21.485317900Z * - Any user, connecting as root, can read or write any data in your cluster.
2019-08-31T12:36:21.485320900Z * - There is no network encryption nor authentication, and thus no confidentiality.
2019-08-31T12:36:21.485323800Z *
2019-08-31T12:36:21.485326700Z * Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v19.1/secure-a-cluster.html
2019-08-31T12:36:21.485329800Z *
2019-08-31T12:36:21.705509100Z *
2019-08-31T12:36:21.705531400Z * ERROR: failed to start server: could not create temp storage: could not open rocksdb instance: IO error: While fsync: a directory: Invalid argument
```
I found similar issue https://github.com/cockroachdb/docs/issues/3184
But nothing helped.

**Comment by ricardocrdb** [comment]
Hey @artem-sydorenko 

I am currently working on recreating your setup and trying to replicate the results. I suspect this error is occurring due to the Windows volume not having a proper volume configured for the Linux kernel in the container to play nice with. Give me some time and I can pin it down.

Cheers,
Ricardo

**Comment by ricardocrdb** [comment]
Hey @artem-sydorenko 

Sorry it took a while, but I had to do a decent amount of digging to get my docker compose to run these volume types properly. I ran this docker-compose.yaml file on a Windows box successfully, and even ran a tpcc workload on it to ensure it was going to hold up to some test data.

The key reason that this is occurring is a limitation in Docker for Windows, as its described in the issue [here](https://github.com/docker/for-win/issues/445). The workaround is the different approach, where the volumes are being set as mount points, and then the Linux containers are able to successfully perform the fsync on these mount points.

Please take a look at my example below, and let me know if you have any other questions:
```
version: '3'

services:
  roach1:
    # Declare the volume on each specific node, citing the volumes listed below, as well as providing the target location.
    volumes:
      - data-volume1:/cockroach-data/data
    image: cockroachdb/cockroach
    container_name: cockroachdb1
    restart: on-failure
    # The command used to start each of the 3 nodes, still need to cockroach init the cluster.
    command: start --insecure --advertise-addr=roach1:26257 --join=roach2:26257,roach3:26257
    # Ports were mapped for external monitoring while running the workload.
    ports:
      - 26260:26257
      - 8083:8080
    networks:
      - roachnet
  roach2:
    volumes:
      - data-volume2:/cockroach-data/data
    image: cockroachdb/cockroach
    container_name: cockroachdb2
    restart: on-failure
    command: start --insecure --advertise-addr=roach2:26257 --join=roach1:26257,roach3:26257
    ports:
      - 26258:26257
      - 8081:8080
    networks:
      - roachnet
  roach3:
    volumes:
      - data-volume3:/cockroach-data/data
    image: cockroachdb/cockroach
    container_name: cockroachdb3
    restart: on-failure
    command: start --insecure --advertise-addr=roach3:26257 --join=roach1:26257,roach2:26257
    ports:
      - 26259:26257
      - 8082:8080
    networks:
      - roachnet
# This defines the network used for the three containers to communicate to each other.
networks:
  roachnet:
# This is where the volumes are defined for each container.
volumes:
  data-volume1:
  data-volume2:
  data-volume3:
```
