### ISSUE TITLE
Connect to cluster from Go?

### ISSUE THREAD

**Issue by hazcod** [cockroachdb/cockroach#41270]
**Is your feature request related to a problem? Please describe.**
I have a 3-node cockroach cluster using the preferred docker-compose for swarm approach.
When connecting to cockroach from `go-pg`, how do I define multiple nodes?
If I only define one, the benefit of a cluster is moot. Writing my own client-based load balancing is complex.

**Describe the solution you'd like**
A load balancer-like concept delivered by cockroach, docker swarm load balancing for services or a better suggestion.

**Comment by rafiss** [comment]
Thank you for raising this!

Our docs currently describe how you could set up load balancing infrastructure like HAProxy in front of a CockroachDB cluster: https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises.html#step-6-set-up-load-balancing

However, I do agree that it would be an interesting direction for us to provide some type of out-of-the-box load balancing solution that doesn't require additional infrastructure.

**Comment by hazcod** [comment]
I originally thought I could use the docker swarm DNS round-robin load balancing when scaling my cockroach services, but since every cockroach service needs different arguments, I can't use the scaling and instead have to define `service1`, `service2`, etc...

**Comment by mattcrdb** [comment]
Like @rafiss said, using a load balancing infrastructure like HAproxy pointing to your docker containers would be one way to do the round-robin load balancing.

By defining service1, service2 etc you mean giving them an alias?

**Comment by hazcod** [comment]
@mattcrdb : I more mean `docker-compose` services, where you can define a single service and scale that to n replicas. But since very cockroach database needs different `--join` arguments and secrets, I don't see that working.

e.g.
```
app:
    image: myapp:latest
    deploy:
        replicas: 3
```
will spin up 3 containers of 'app'. If the proxy queries for 'app', it will get one of the three instances based on round-robin DNS load balancing.

**Comment by ricardocrdb** [comment]
Hey @hazcod 

Have a look at our example `docker-compose.yml` file, which contains the definition for the 3 services, but also a specific join flag. Looking at lines [#20](https://gist.github.com/danmrichards/e28cb8b0356fb768e7bc6d9404a5ef6a#file-docker-compose-yml-L20) to [#33](https://gist.github.com/danmrichards/e28cb8b0356fb768e7bc6d9404a5ef6a#file-docker-compose-yml-L33)

```
command: start --insecure --join=roach1
    volumes:
      - ./cockroach-data/roach2:/cockroach/cockroach-data
    depends_on:
      - roach1
    networks:
      roachnet:
        aliases:
          - roach2

  roach3:
    container_name: roach3
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure --join=roach1
```

you can see that the command for each container is running the join to the first container name, roach1. since the 3 containers each have unique names, configuring he HA proxy to do the load balancing to the three containers should be fairly straightforward. Let me know if there are any other questions.
