### ISSUE TITLE
kubernetes: support pod az in --locality flag

### ISSUE THREAD

**Issue by DuskEagle** [cockroachdb/cockroach#41613]
Clusters created by our Kubernetes manifests do not contain availablitiy zone information in their `--locality` flags. This could cause ranges to not be replicated across different availability zones within a region, potentially causing a single zone outage to lead to unavailable data. This applies both to single-region and multi-region deployments.

The problem is that in a Kubernetes cluster with nodes in multiple zones, we cannot know which zone a pod will run in until it is scheduled. Therefore, we need to determine the availability zone of a pod in an [init container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/). The init container will check which AZ the pod is running in, and save that value for the main Cockroach container to read later. 

I don't know of a cloud-agnostic way to determine a pod's availability zone in Kubernetes. But for any given Cloud provider, we could query the instance metadata server for that provider to determine the AZ of the node the pod is running in. 

For example, an init container for AWS could look like this:

```
initContainers:
- command:
  - sh
  - -ecx
  - echo "aws-$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone/)"
    > /etc/cockroach-env/zone
  image: byrnedo/alpine-curl:0.1
  name: locality-container
  volumeMounts:
  - mountPath: /etc/cockroach-env
    name: cockroach-env
```

Or for GCP:

```
initContainers:
- command:
  - sh
  - -ecx
  - echo "gcp-$(curl -HMetadata-Flavor:Google http://metadata.google.internal/computeMetadata/v1/instance/zone
    | awk -F/ '{print $4}')" > /etc/cockroach-env/zone
  image: byrnedo/alpine-curl:0.1
  name: locality-container
  volumeMounts:
  - mountPath: /etc/cockroach-env
    name: cockroach-env
```

This writes the AZ information to a VolumeMount `/etc/cockroach-env`. This can then be read by the CockroachDB pods when they start:

```
containers:
- command:
  - /bin/bash
  - -ecx
  - exec /cockroach/cockroach start --certs-dir=/cockroach/cockroach-certs
    --locality=region=<region>,az=$(cat /etc/cockroach-env/zone) --advertise-host $(hostname -f) --join <join-flag>
  volumeMounts:
  - mountPath: /etc/cockroach-env
    name: cockroach-env
volumes:
- emptyDir: {}
  name: cockroach-env
```

If we provide a single init container that could either use native Kubernetes constructs to determine a pod's zone, or knew how to query all the major cloud providers' instance metadata servers to determine the zone of a pod, then any customers who use our Kubernetes manifests to deploy CockroachDB would benefit from having the locality flags set properly on their nodes by default.
