### ISSUE TITLE
Secure cluster behind nginx-ingress in k8s

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/cockroach#49532]
**Describe the problem**
I am getting  `too many redirects` when trying to access secure cockroachdb cluster behind ingress-nginx using [helm chart](https://hub.helm.sh/charts/stable/cockroachdb).

Please describe the issue you observed, and any steps we can take to reproduce it:

It is happening because tls.enabled == secure cluster with tls termination.
Same thing i got with [argo cd](https://github.com/argoproj/argo-cd/issues/2953#issuecomment-602898868) and solved using --insecure flag (Insecure - just about tls termination)
So i have to use insecure cluster behind ingress (losing auth screen, users with passwords etc) or secure cluster without ingress inside k8s (And i have to manage certificates, use not 80 and 443 ports, it's painful)

**To Reproduce**

1. Setup basic k8s cluster
2. Setup nginx-ingress, cert-manager
3. Setup secure cockroachdb cluster
4. Create k8s Ingress for cockroachdb service
5. Try to access admin panel

**Expected behavior**
I can disable tls termination in web ui, but don't lose security cluster benefits

**Additional data / screenshots**
- I am using helm charts:
  - https://hub.helm.sh/charts/stable/cockroachdb
  - https://hub.helm.sh/charts/stable/nginx-ingress
  - https://hub.helm.sh/charts/jetstack/cert-manager

**Environment:**
 - CockroachDB version 20.1
 - Server OS: Debian 10

**Comment by knz** [comment]
xref #44842

**Comment by mihneastaub** [comment]
any updates on this issue?

**Comment by knz** [comment]
We've not found the direct cause of the issue yet, but you might have interest in #74329.

**Comment by udnay** [comment]
@sergeyshaykhullin can you connect to the web ui from inside the cluster if you do portforwarding and bypass the nginx ingress?

I assume you have something like
`external request (https)` -> `nginx ingress (tls termination)` -> `web ui (http)` and the redirect loop is happening at the CRDB side?

**Comment by udnay** [comment]
@mihneastaub or @sergeyshaykhullin can you also provide your k8s nginx annotations?

**Comment by mihneastaub** [comment]
@udnay I'm using istio gateway for the ingress controller.

**Comment by sergeyshaykhullin** [comment]
```yaml
metadata:
    annotations:
      kubernetes.io/tls-acme: "true"
      meta.helm.sh/release-name: crdb
      meta.helm.sh/release-namespace: crdb
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
      nginx.ingress.kubernetes.io/service-upstream: "true"
```
