### ISSUE TITLE
Add ingress and serviceMonitor values to helm chart

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/cockroach#49533]
**Is your feature request related to a problem? Please describe.**
Most of charts with web ui has `ingress` value, it is easy to use and very compact.
Same thing with Prometheus ServiceMonitor

**Describe the solution you'd like**
Add
```
ingress:
  enabled: ...
  hosts: [...]
  tls: [...]
  annotations: [...]
  ...etc
```

```
monitoring/prometheus/...:
  serviceMonitor:
    enabled: ...
    ...etc
```
values to cockroach helm chart

**Additional context**
Helm charts with ServiceMonitor and(or) Ingress support i used:
- https://hub.helm.sh/charts/argo/argo-cd
- https://hub.helm.sh/charts/stable/grafana
- https://hub.helm.sh/charts/jaegertracing/jaeger-operator
- https://hub.helm.sh/charts/bitnami/prometheus-operator
- https://hub.helm.sh/charts/stable/rabbitmq-ha
- https://hub.helm.sh/charts/jetstack/cert-manager
- https://hub.helm.sh/charts/stable/nginx-ingress
- https://hub.helm.sh/charts/loki/loki
- https://hub.helm.sh/charts/loki/promtail
- https://hub.helm.sh/charts/stable/redis-ha
