### ISSUE TITLE
Helm chart with users and databases provisioning

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/cockroach#49531]
**Is your feature request related to a problem? Please describe.**
Add to helm chart ability to provision users and databases

**Describe the solution you'd like**
```
conf:
  users:
  - username: 123
    password: 456
    ...
  databases:
  - name: 789
     grant: 123
     ...
```

**Describe alternatives you've considered**
Add value to specify secrets for provisioning

**Additional context**
I am trying to use cockroachdb [helm chart](https://hub.helm.sh/charts/stable/cockroachdb), but not comfortable with users/databases provisioning.
I have to start sql client and create databases manually.
Example in [zalando/postgres-operator](https://github.com/zalando/postgres-operator/blob/master/docs/user.md#create-a-manifest-for-a-new-postgresql-cluster)
