### ISSUE TITLE
Nodes are infinetly rejoining

### ISSUE THREAD

**Issue by sergeyshaykhullin** [cockroachdb/cockroach#57202]
**Describe the problem**
The problem is that nodes deployed with helm chart rejoining some times in a day

It might be an insufficient memory limits, but nodes are using up to 80% of it

**To Reproduce**

Values template

```yaml
statefulset:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 256M
    limits:
      cpu: 200m
      memory: 512M

service:
  public:
    annotations:
      consul.hashicorp.com/service-sync: "true"
      consul.hashicorp.com/service-name: cockroachdb
      consul.hashicorp.com/service-port: grpc

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: lestencrypt
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
  hosts: [**omitted**]
  tls:
  - hosts: [**omitted**]
    secretName: cockroachdb-tls

serviceMonitor:
  enabled: true

storage:
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: **omitted**

tls:
  enabled: false
```

**Expected behavior**
CockroachDB cluster is stable

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/46970457/100518860-65aaf680-31a5-11eb-9885-2369eb76b4f6.png)
![image](https://user-images.githubusercontent.com/46970457/100519239-c0dde880-31a7-11eb-9697-809365661049.png)

**Environment:**
 - CockroachDB version: 20.2
 - Server OS: Kubernetes helm chart, official image

**Additional context**

Which one additional information i have to provide?
