### ISSUE TITLE
logs: support YAML arrays in channel selection for log configuration

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#58958]
When configuring logs using the new `--log=` flag, we need to pass a list of channels as a string when configuring a file group sink:

```
sinks:
 file-groups:
   security:
     channels: "SESSIONS, USER_ADMIN, PRIVILEGES, SENSITIVE_ACCESS"
```

It would be nice to support an array in the YAML itself:
```
sinks:
 file-groups:
   health:
     channels:
       - HEALTH
       - OPS
```
or

```
sinks:
 file-groups:
   health:
     channels: [HEALTH, OPS]
```

cc @thtruo
