### ISSUE TITLE
logs: Unable to get SESSIONS and USER_ADMIN channels to write to file_group sink

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#58971]
I created a single node cluster to test the logging channel changes and I'm unable to see the SESSIONS and USER_ADMIN channels in a dedicated file-group sink.

I specified log configs in a yaml file:

```
file-defaults:
  dir: logs          
  filter: WARNING   
  redact: false       
  redactable: false   
  max-file-size: 10MB  
  max-group-size: 100MB

sinks:
 file-groups:
   health:
     channels: "HEALTH, OPS"
     format: json
   sec:
     channels: "USER_ADMIN, SESSIONS"
     format: json
```

I then started a secure single node cluster: 
```
./cockroach start-single-node --certs-dir=certs --store=data --log="$(cat logs.yaml)" --advertise-addr=<redacted>
```

This was using the latest master build:
```
build:               CCL v21.1.0-alpha.1-975-gc3ed36b928 @ 2021/01/13 01:03:22 (go1.15.6)
```

I then connected to the cluster and enabled session and connection logging. I also created a user:
```
./cockroach sql --url postgres://root@<redacted>:26257?sslmode=verify-full --certs-dir=certs
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.1.0-alpha.1-975-gc3ed36b928 (x86_64-unknown-linux-gnu, built 2021/01/13 01:03:22, go1.15.6) (same version as client)
# Cluster ID: ea0c96c6-aa90-4aff-916d-e8c4ac4fe8e6
#
# Enter \? for a brief introduction.
#
root@:26257/defaultdb> SET CLUSTER SETTING server.auth_log.sql_connections.enabled = true;
SET CLUSTER SETTING

Time: 10ms total (execution 10ms / network 0ms)

root@:26257/defaultdb> SET CLUSTER SETTING server.auth_log.sql_sessions.enabled = true;
SET CLUSTER SETTING

Time: 10ms total (execution 10ms / network 0ms)

root@:26257/defaultdb> create user piyush with password test;
CREATE ROLE

Time: 81ms total (execution 80ms / network 0ms)
```

I then disconnected my sql shell and connected again in order to trigger an event for the SESSIONS channel. However, when I inspected my logs directory, I did not see the expected log file symlink (or any files) `cockroach-sec.<info>.log`. Am I doing something wrong? I was able to see the `cockroach-health.log` symlink and log files - why is the other file not showing?

cc @thtruo
