### ISSUE TITLE
SQLSTATE: 42601 during the import pgdump process

### ISSUE THREAD

**Issue by fragaLY** [cockroachdb/cockroach#59473]
**The problem**

Hello, everyone,

I faced a problem related to dump importing process.

> root@:26257/defaultdb> import pgdump 'http://minio-server:9000/dumps/dump.sql';
> ERROR: postgres parse error: at or near "superuser": syntax error
> SQLSTATE: 42601
> DETAIL: source SQL:
> ALTER ROLE "user" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD '$mypassword'
 
 Diving deeper in dump.sql:
 
 `
SET default_transaction_read_only = off;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
DROP DATABASE "hapi-fhir";
DROP ROLE "user";
CREATE ROLE "user";
ALTER ROLE "user" WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD '$PASSWORD';
...
`

**To Reproduce**

Firstly, I've created a dump of 1kk data from Postgres, using the following command:
`pg_dumpall -c --dbname=postgresql://user:password@localhost:5432/hapi-fhir > dump.sql`

Then started a cockroach and min.io using docker-compose:
```
version: '3.7'

services:

  cockroach1:
    container_name: cockroach1
    image: cockroachdb/cockroach:v20.1.11
    volumes:
      - ./data/node_1:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"

  minio-server:
    container_name: minio-server
    image: minio/minio
    volumes:
      - ./data/minio-server:/data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
      - MINIO_REGION_NAME=us-east-1
    command: server /data
```

After that, I created a bucket and uploaded a dump directly to min.io using web-interface via localhost:9000

In the next step, I ran the mc client and changed it's config.json with correct accesskey and secretkey for localhost:9000 and set up a public policy for bucket:

`mc policy set public local/dumps
`
Connected to cockroach:
`docker exec -it cockroach1 ./cockroach sql --insecure
`

And running a script to import a dump:
`CREATE DATABASE IF NOT EXISTS $DB_NAME;
USE $DB_NAME;
IMPORT PGDUMP 'http://minio-server:9000/dumps/dump.sql';`

**Expected behavior**
The dump successfully imported.

**Environment:**
 - CockroachDB version v.20.1.11
 - Server OS: Win
 - Client app: cockroach sql

***Additional notes***

Using Postgres dump easily imported. On Cockroach not.
