### ISSUE TITLE
DB Console returns 502 Bad Gateway error behind reverse proxy

### ISSUE THREAD

**Issue by naderelshehabi** [cockroachdb/cockroach#65598]
**Describe the problem**

DB Console always returns 502 bad gateway error when served behind Traefik reverse proxy

**To Reproduce**

1. Setup **secure** cluster in docker containers, with appropriate traefik labels to serve HTTP DB Console
2. Setup Traefik reverse proxy and add CockroachDB SSL certificate to Traefik SSL store
3. Access via web browser

If possible, provide steps to reproduce the behavior:

Steps provided above. You can see my exact setup in the following repository:
https://github.com/naderelshehabi/docker-containers/tree/main/cockroachdb

I'm using Traefik to serve local containers via localhost on my laptop. Since CockroachDB Web DB console can't be served via path under localhost, I'm using an only revrse DNS to server it on a separate domain name (cockroachdb.127.0.0.1.nip.io, will point to localhost).

The DNS routing works fine. Traefik serves the correct SSL sertificate generated by CockroachDB to the correct node. Yet, the DB Console returns 502 bad gateway. I even used the certificate that's generated by the node's command (cockroach cert), and it didn't work.

IF I publish 8080 port, and access the console without the reverse proxy, it works fine.

**Expected behavior**
DB Console displayed correctly with no error/

**Additional data / screenshots**
N/A

CockroachDB logs show nothing. Traefik logs show "Failed TLS Handshake, unknown certificate" error. Based on their documentation, this error is from the client container, not from Traefik itself.

**Environment:**
 - CockroachDB version 2.0.10
 - Server OS: Linux / docker
 - Client app DB Console via web browser

**Additional context**
What is the host name the server uses to validate the SSL? Is there a way to skip the SSL verify process without goin insecure mode?

**Comment by knz** [comment]
Traefik is confused by the TLS certificates you've used for the CockroachDB http port.

If you are using a self-signed CA for crdb HTTP, you need to tell Traefic what CA cert to use to validate the crdb http server. What is your TLS config?

**Comment by naderelshehabi** [comment]
Hi knz.

I'm using a certificate signed by the CockroachDB CA that's used to generate the nodes' certificates as well. I even set the `insecureSkipVerify: true`, on Traefik side, but didn't make a difference.

For the record, here is my Traefik TLS setting:
```
http:
  serversTransports:
    cockroachdb-serverTransport:
      serverName: cockroachdb.127.0.0.1.nip.io
      insecureSkipVerify: true
      rootCAs:
        - /run/secrets/ca.crt
      certificates:
        - certFile: /run/secrets/cockroachdb.crt
          keyFile: /run/secrets/cockroachdb.key

tls:
  certificates:
    - certFile: /run/secrets/localhost.crt
      keyFile: /run/secrets/localhost.key
      stores:
        - default
    - certFile: /run/secrets/cockroachdb.crt
      keyFile: /run/secrets/cockroachdb.key
      stores:
        - default
  options:
    cockroachdb-options:
      clientAuth:
        caFiles:
          - /run/secrets/ca.crt
        clientAuthType: RequestClientCert
      sniStrict: false
  stores:
    default:
      defaultCertificate:
        certFile: /run/secrets/localhost.crt
        keyFile: /run/secrets/localhost.key
```
The correct certificate is served by the browser, but I believe what is served between the browser and traefik, is different from the certificate used between Traefik and cockroachdb container. The latter is served by the container itself.

This is what Traefik logs show on debug mode:
```
10.0.0.2 - - [24/May/2021:19:28:45 +0000] "GET / HTTP/2.0" 502 11 "-" "-" 6 "cockroachdb-admin@docker" "https://10.0.1.56:8080" 2ms
time="2021-05-24T19:28:45Z" level=debug msg="mime: no media type" middlewareName=cockroachdb-compress@docker middlewareType=Compress
time="2021-05-24T19:28:45Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_c3130=https://10.0.1.56:8080\"],\"Sec-Ch-Ua\":[\"\\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Chromium\\\";v=\\\"90\\\", \\\"Google Chrome\\\";v=\\\"90\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36\"],\"X-Forwarded-Host\":[\"cockroachdb.127.0.0.1.nip.io\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"d3fefd5b0ae7\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"cockroachdb.127.0.0.1.nip.io\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:46284\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2021-05-24T19:28:45Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="https://10.0.1.56:8080" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\",\"RawFragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"en\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_c3130=https://10.0.1.56:8080\"],\"Sec-Ch-Ua\":[\"\\\" Not A;Brand\\\";v=\\\"99\\\", \\\"Chromium\\\";v=\\\"90\\\", \\\"Google Chrome\\\";v=\\\"90\\\"\"],\"Sec-Ch-Ua-Mobile\":[\"?0\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36\"],\"X-Forwarded-Host\":[\"cockroachdb.127.0.0.1.nip.io\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"d3fefd5b0ae7\"],\"X-Real-Ip\":[\"10.0.0.2\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"cockroachdb.127.0.0.1.nip.io\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"10.0.0.2:46284\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2021-05-24T19:28:45Z" level=debug msg="'502 Bad Gateway' caused by: dial tcp 10.0.1.56:8080: connect: connection refused"
```

It looks like Traefik is trying to reach the container via the IP which the container refuses to connect by, since the http-addr is by the host name. Is there a way to have DB Console skip this verification somehow?
