### ISSUE TITLE
All Indexes aren't picked up for some time

### ISSUE THREAD

**Issue by Bessonov** [cockroachdb/cockroach#66257]
Hello Cockroachers!

I've a strange issue that no one index is used for some time.

**Describe the problem**

On fresh database start with docker and usual migration with knex, the queries are very slow. Explain show, that `table@primary` is used and db do full table scan. If I specify a index to use with `tyble@myindex`, then it works as expected. Some time after or if I drop/recreate one of indexes, then it seems like that the problem goes away. I'm experiencing this behavior with 20.1.9, but also with 21.1.1.

We had very similar problem with update from 20.1.3 to 20.2.x with downgrade option enabled - the performance was 100x worse, even after 2 hours later with nearly empty database. Because of time constraint we doesn't analysed it further and upgraded instead to the ATM latest 20.1.x version of crdb: 20.1.9.

**To Reproduce**

I'm not able to reproduce it constantly, but there is about 10% chance to run in this scenario. At the core, it's just a fresh docker instance with migrations. Probably important: I run performance benchmarks for the app, so multiple queries arrived at same time.

**Expected behavior**
-

**Additional data / screenshots**

I'm not sure that this is a common problem, because, I mean, if it was a common problem, then many people were suffer from it. Therefore I assume I do something that leads to some unusual state. I can provide additional information - what would be helpful? Which settings are interesting?

**Environment:**
 - CockroachDB version: 20.1.9 in docker
 - Server OS: [e.g. Linux/Distrib]: Ubuntu 18.04 host
 - Client app [e.g. `cockroach sql`, JDBC, ...]: knex with PG driver

docker-compose definition:
```yaml
  cockroachdb:
    image: cockroachdb/cockroach:v20.1.9
    hostname: cockroachdb
    container_name: ${TESTSDK_PROJECT}_cockroachdb
    volumes:
      - 'cockroachdb:/cockroach/cockroach-data'
    command: start-single-node --insecure --cache=512m --max-sql-memory=512m
    healthcheck:
      test: ['CMD', './cockroach', 'sql', '--insecure']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
[...]
volumes:
  cockroachdb:
```
