### ISSUE TITLE
ui: web console cluster overview page fails to load after removing nodes from cluster

### ISSUE THREAD

**Issue by nick-jones** [cockroachdb/cockroach#69029]
**Describe the problem**

After creating a 9 node cluster with 3 localities, and then removing the nodes in one of those localities, the "Cluster Overview" page fails to load. The following JS error is logged to the browser console:

```
Error: Unreachable point with value: 7 
    S_ http://localhost:8080/bundle.js:1264
    ny http://localhost:8080/bundle.js:1264
    render http://localhost:8080/bundle.js:1264
    value http://localhost:8080/bundle.js:1190
    $i http://localhost:8080/bundle.js:1223
    Zi http://localhost:8080/bundle.js:1223
    Ps http://localhost:8080/bundle.js:1223
    Nc http://localhost:8080/bundle.js:1223
    Mc http://localhost:8080/bundle.js:1223
    wc http://localhost:8080/bundle.js:1223
    o http://localhost:8080/bundle.js:1223
    unstable_runWithPriority http://localhost:8080/bundle.js:1231
    Ko http://localhost:8080/bundle.js:1223
    $o http://localhost:8080/bundle.js:1223
    Zo http://localhost:8080/bundle.js:1223
    Oc http://localhost:8080/bundle.js:1223
    notify http://localhost:8080/bundle.js:14
    notifyNestedSubs http://localhost:8080/bundle.js:14
    handleChangeWrapper http://localhost:8080/bundle.js:14
    g http://localhost:8080/bundle.js:1195
    am http://localhost:8080/bundle.js:1258
    p http://localhost:8080/bundle.js:1207
    r http://localhost:8080/bundle.js:1207
    dispatch http://localhost:8080/bundle.js:1195
    refresh http://localhost:8080/bundle.js:1258
bundle.js:1223:77167
    gs http://localhost:8080/bundle.js:1223
    callback http://localhost:8080/bundle.js:1223
    xa http://localhost:8080/bundle.js:1223
    ka http://localhost:8080/bundle.js:1223
    Dc http://localhost:8080/bundle.js:1223
    unstable_runWithPriority http://localhost:8080/bundle.js:1231
    Ko http://localhost:8080/bundle.js:1223
    Lc http://localhost:8080/bundle.js:1223
    wc http://localhost:8080/bundle.js:1223
    o http://localhost:8080/bundle.js:1223
    unstable_runWithPriority http://localhost:8080/bundle.js:1231
    Ko http://localhost:8080/bundle.js:1223
    $o http://localhost:8080/bundle.js:1223
    Zo http://localhost:8080/bundle.js:1223
    Oc http://localhost:8080/bundle.js:1223
    notify http://localhost:8080/bundle.js:14
    notifyNestedSubs http://localhost:8080/bundle.js:14
    handleChangeWrapper http://localhost:8080/bundle.js:14
    g http://localhost:8080/bundle.js:1195
    am http://localhost:8080/bundle.js:1258
    p http://localhost:8080/bundle.js:1207
    r http://localhost:8080/bundle.js:1207
    dispatch http://localhost:8080/bundle.js:1195
    refresh http://localhost:8080/bundle.js:1258
```

**To Reproduce**

Using the following `docker-compose.yaml`:

```yaml
version: "3"

services:
  cockroachdb-0:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=aws" --advertise-addr=cockroachdb-0 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    ports:
      - "8080:8080"
    expose:
      - "26257"
  cockroachdb-1:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=aws" --advertise-addr=cockroachdb-1 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-2:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=aws" --advertise-addr=cockroachdb-2 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-3:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=gcp" --advertise-addr=cockroachdb-3 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-4:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=gcp" --advertise-addr=cockroachdb-4 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-5:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=gcp" --advertise-addr=cockroachdb-5 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-6:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=azure" --advertise-addr=cockroachdb-6 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-7:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=azure" --advertise-addr=cockroachdb-7 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-8:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --locality="cloud=azure" --advertise-addr=cockroachdb-8 --join=cockroachdb-0,cockroachdb-1,cockroachdb-2,cockroachdb-3,cockroachdb-4,cockroachdb-5,cockroachdb-6,cockroachdb-7,cockroachdb-8
    expose:
      - "26257"
  cockroachdb-init:
    image: cockroachdb/cockroach:v21.1.7
    entrypoint:
      - "/bin/bash"
      - "-c"
      - >-
        while true; do
          echo "initialising cluster.."
          /cockroach/cockroach init --insecure --host="cockroachdb-0:26257"
          code=$$?
          if [[ $$code -eq 0 ]]; then
            break
          fi
          sleep 1
        done
    expose:
      - "26257"
```

```
$ docker-compose up --force-recreate
```

Wait for the cluster to initialise and open http://localhost:8080

<img width="1209" alt="Screenshot 2021-08-17 at 10 57 00" src="https://user-images.githubusercontent.com/350792/129708784-774fbab2-2fb7-4b53-bac5-d677398503da.png">

All good so far..

Now:

```
$ docker-compose kill cockroachdb-6 cockroachdb-7 cockroachdb-8
```

After a short wait, refresh the console.. and you'll be met with:

<img width="1204" alt="Screenshot 2021-08-17 at 10 59 38" src="https://user-images.githubusercontent.com/350792/129710569-2c7fd216-0445-4166-bbd6-0c3af4a05d8d.png">

The page fails to load.

Note I'm specifically not killing the node with 8080 forwarded. I can reach other parts of the console (e.g. http://localhost:8080/#/metrics/overview/cluster)

**Expected behavior**

Overview page loads. Even if the cluster is not in a healthy place, or the way I've got things setup is wrong, I'd still expect more than a blank screen.

**Environment:**
 - CockroachDB version: v21.1.7
 - Server OS: Linux
