### ISSUE TITLE
sql: add support for Hasura

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#72407]
For anyone pursuing updates here, last I've heard is that Hasura is currently working towards making integrations with other databases easier. As soon as we can get any update, we'll look to get the ball moving on this again.

We know we have some features that we need to implement (and are looking to get a lot of these done in the next 6-12 months!) and we hope we can get this working for all of you soon!

----

# Prototype branches

* CockroachDB: https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:ext / #76197
* Hasura: https://github.com/hasura/graphql-engine/compare/master...otan-cockroach:crdb

# List of needed changes so far:

- [x] (Hasura workaround possible) User-defined functions are needed for `hasura_gen_uuid()` and `insert_event_log`. (https://github.com/hasura/graphql-engine/commit/af13f962c351637217acc8f099f349995c0ae778)
- [ ] (Hasura workaround possible?) We do not support the `ON CONFLICT ((expr))` clause (https://github.com/hasura/graphql-engine/commit/dfab4461f99c7e0801c815e594a2ab8e8c1a367e) -- https://github.com/cockroachdb/cockroach/issues/67893
- [x] (Hasura workaround possible?) We do not support `ON UPDATE SKIP LOCKED` (https://github.com/hasura/graphql-engine/commit/35366c1907433205ff001a25204b68ffe8cb8466) -- #40476
- [x] (Hasura workaround possible) We do not support aliasing tables to `index`, but PG does (https://github.com/hasura/graphql-engine/commit/0439afe4fe6f89ccea278195263ab7686faa155a)
- [x] (Hasura workaround possible but CockroachDB fix possible) We need to feign support for pgcrypto, or make hasura not check for it (https://github.com/cockroachdb/cockroach/commit/d09ea03b46b72b9481f0d848ce31725ad14252ef). We support some of the pgcrypto builtins, but we'll have to check if the other ones are needed to. See [CRDB-120](https://cockroachlabs.atlassian.net/browse/CRDB-120).
- [x] (Hasura workaround doable for someone versed at Haskell; CockroachDB proper fix labour intensive + major behaviour change which is backwards compat) We do not support the JSON type (we convert everything to JSONB automatically). Hasura relies on JSON wire format, which means I needed to make these scary changes to CRDB as a quick hack to pretend we write json. (https://github.com/cockroachdb/cockroach/commit/63041ba3ca0cf64fbcfa47cac81f8a57b2380f58, https://github.com/cockroachdb/cockroach/commit/e64bc44fc46008c67fb61c6fcdb137f5d8a2b1be) Hasura relies on `AltJ` / their own thing I don't totally grok to do this decoding, not sure how to change it (it's their own homegrown library: https://github.com/hasura/pg-client-hs). Hasura needs to recognise the "1" at the front is just part of the binary protocol. (see https://github.com/cockroachdb/cockroach/issues/88355)
- [x] (CockroachDB issue)This query finishes in 20mins on CRDB: https://gist.github.com/otan/498fc5fef15f6147be5ae1f429ca146f. Root cause is `pg_catalog.col_description` which is slow. disabled. https://github.com/hasura/graphql-engine/commit/5da773c50f55e53ae36b7cbda3083b66a5a504ae (see https://github.com/cockroachdb/cockroach/issues/87947)
- [x] (CockroachDB issue) CockroachDB does not support `pg_get_functiondef`. We should return NULL. https://github.com/hasura/graphql-engine/commit/74159c218153c3857efd813ffff391c1a0005409
- [ ] (CockroachDB issue) need to add ` --skip-schema-setup` to pytest command, because `drop schema if exists hge_tests cascade; create schema hge_tests;` in the same txn doesn't work.
- [x] (Hasura issue) psycopg on Hasura doesn't recognise CockroachDB - see https://github.com/cockroachdb/cockroach/commit/5349071c2125c3c37200d5bbd563e15b464f647d

At present time, I have the Haskell engine up, but the pytest has UDFs all over the test suite. Impossible to get around - we need to implement them or the Hasura suite needs to not use them.

Epic CRDB-11916

Jira issue: CRDB-11915

**Comment by rafiss** [comment]
> We do not support the ON CONFLICT ((expr)) clause, or the ON CONFLICT ... DO UPDATE clause.

Could you clarify the second half of that sentence? CRDB does have ON CONFLICT ... DO UPDATE: https://www.cockroachlabs.com/docs/stable/insert.html#on-conflict-clause

**Comment by otan** [comment]
Huh we'll I had a syntax error when I tried. Maybe it's fine.

**Comment by rafiss** [comment]
> This query finishes in 20mins on CRDB: https://gist.github.com/otan/498fc5fef15f6147be5ae1f429ca146f. Root cause is pg_catalog.col_description which is slow.

that is affecting activerecord too https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/234

One improvement is to resolve https://github.com/cockroachdb/cockroach/issues/69495 -- I think we should prioritize this since it's coming up for so many different ORMs.

**Comment by rafiss** [comment]
Here's an example of how to improve the introspection query so it doesn't use `col_description`

> Huh well I had a syntax error when I tried just removing ((expr)). Maybe it's fine.

It'd need to be changed to `ON CONFLICT (constraint_name) DO UPDATE`

**Comment by dbettin** [comment]
Is this a feature that is actively being worked on? Or is it a "maybe sometime in the future" type of feature?

**Comment by otan** [comment]
Hi @dbettin! We've been trying to get in contact with Hasura as most of the changes will probably have to be on their side (I've even tried skirting the waters by submitting a PR: https://github.com/hasura/graphql-engine/pull/7788). Unfortunately we haven't heard any updates recently.

**Comment by gunrein** [comment]
Hey @otan - thanks for raising the PR, this is great! I joined Hasura recently to lead product and was just introduced via email to Vy, Andy, and Mark from Cockroach earlier today so this is timely. We're eager to work with you on this effort. Right now we're working on an improvement that'll make it easier to collaborate with you on supporting Cockroach and we'd love to engage around that as soon as it is ready to try out. It is fairly research heavy at the moment so timelines are hard to predict, but sometime in the next couple of months is likely.

**Comment by dennislaviolette** [comment]
Hi @otan - My name is Dennis and I work with @gunrein on the product team here at Hasura.  There is quite the buzz here regarding your recent [merge](https://github.com/hasura/graphql-engine/pull/7788).

We are very much looking forward to working more closely with you in an effort to holistically support CokcroachDB via the Hasura GraphQL service.  At present the absence of a proper validation framework and existence of support documentation from Hasura specifically means we have some planning/research to do.

I will be following up via email to setup a more thorough call so we can get a better scope of how best we can support CockroachDB moving forward.

**Comment by vy-ton** [comment]
@dennislaviolette Thanks for the update. Please include kernfeld@cockroachlabs.com and vy@cockroachlabs.com

**Comment by GavinRay97** [comment]
In the event anyone wants to test this, here is a Docker Compose to set up Hasura + Cockroach.

You can use the `Connect DB` from Hasura web console at http://localhost:8080 to (try) to add a new Postgres DB from the `COCKROACHDB_URL` environment variable:

```yaml
version: "3.6"

services:
    cockroach:
        image: cockroachdb/cockroach:v21.2.4
        ports:
            - "26257:26257"
            - "8070:8080"
        command: start-single-node --insecure
        volumes:
            - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"

    postgres:
        image: postgres:14
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword

    graphql-engine:
        image: hasura/graphql-engine:v2.1.1
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"
        restart: always
        environment:
            COCKROACHDB_URL: postgresql://root@cockroach:26257/defaultdb?sslmode=disable
            HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/postgres
            HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:postgrespassword@postgres:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

volumes:
    db_data:
```

![image](https://user-images.githubusercontent.com/26604994/151592485-9edd7770-94a8-454a-aa2e-32bf0ed463bb.png)
