### ISSUE TITLE
Using log config file, OPS channel messages are not logged when in default file-group with format and redact set

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#79893]
**Describe the problem**
This issues exists in version 21.1.16 (still exists in 21.1.18). It does not exist in 21.2.8.

If `OPS` is included in `channels` under the `default` file-group, `OPS` messages are not logged when `format` and `redact` are set. The issue was encountered using a log config yaml file with:

```
sinks:
  file-groups:
    default:
      channels: [OPS, HEALTH]
      format: crdb-v2
      redact: false
```

The workaround in 21.1.16 is to use a separate file-group/channel for `ops`, however, this will log `OPS` messages to `cockroach-ops.log`: 

```
sinks:
  file-groups:
    default:
      channels: [HEALTH]
      format: crdb-v2
      redact: false
    ops:
      channels: [OPS]
      redact: false
```

**To Reproduce**

The user script searched for this `OPS` message:

```
Node will now attempt to join a running cluster, or wait for \`cockroach init\`\.
```
[after.yml.txt](https://github.com/cockroachdb/cockroach/files/8482314/after.yml.txt)
[before.yml.txt](https://github.com/cockroachdb/cockroach/files/8482315/before.yml.txt)

Using log config file `before.yml` which has the below `default` file-group, the above `OPS` message is logged to `cockroach.log`.

```
sinks:
  file-groups:
    default:
      channels: [DEV, OPS, HEALTH, SQL_SCHEMA, USER_ADMIN, PRIVILEGES]
```

Using log config file `after.yml`  which has the below `default` file-group, the above `OPS` message is NOT logged to `cockroach.log`.

```
sinks:
  file-groups:
    default:
      channels: [OPS, HEALTH]
      format: crdb-v2
      redact: false
```

**Expected behavior**

This log config writes the above `OPS` message in `cockroach.log`

```
sinks:
  file-groups:
    default:
      channels: [OPS, HEALTH]
      format: crdb-v2
      redact: false
```

**Environment:**
 - CockroachDB version 21.1.16

**Additional context**
The user's upgrade script did not work.

Jira issue: CRDB-15871
