### ISSUE TITLE
Scripts from `docker-entrypoint-initdb.d` are not executed when using `--store=type=mem,size=0.25` for `start-single-node`

### ISSUE THREAD

**Issue by janpio** [cockroachdb/cockroach#80005]
We have successfully been using an adapted Docker image with a file in `/docker-entrypoint-initdb.d` to create a user and apply the suggested testing configuration: https://github.com/prisma/engine-images/blob/7695bfcc990b5f91cf5d86b15ec95fc3b129f709/cockroach/cockroach.Dockerfile

Now we were also recommended to use `--store=type=mem,size=0.25` as an additional argument to `start-single-node --insecure` and noticed that a) the user is not present any more and b) all the configuration is default - so I think our `.sql` file from our image is not run correctly.

Reproduction is possible via this docker-compose:
```
version: "3"
services:
  test-db-cockroachdb:
    image: prismagraphql/build:cockroach-custom
    restart: always
    command: start-single-node --insecure
    ports:
      - "26257:26257"
    networks:
      - engine-tests

  test-db-cockroachdb-mem:
    image: prismagraphql/build:cockroach-custom
    restart: always
    command: start-single-node --insecure --store=type=mem,size=0.25
    ports:
      - "26258:26257"
    networks:
      - engine-tests

networks:
  engine-tests: null
```

The `prismagraphql/build:cockroach-custom` is our customized image that adds the `.sql` file to `cockroachdb/cockroach-unstable:v22.1.0-alpha.1`, it is built via https://github.com/prisma/engine-images/blob/7695bfcc990b5f91cf5d86b15ec95fc3b129f709/cockroach/cockroach.Dockerfile linked above.
