### ISSUE TITLE
' %!(BADWIDTH)' prepended to value when inserting into character(10485760) column

### ISSUE THREAD

**Issue by markddrake** [cockroachdb/cockroach#84531]
**Describe the problem**

' %!(BADWIDTH)' prepended to value when inserting into character(10485760) column

**To Reproduce**

```
C:\Development\YADAMU>psql -Uroot -hyadamu-db2  -p26257 -d yadamu
psql (13.3, server 13.0.0)
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

yadamu=> select version();
                                       version
-------------------------------------------------------------------------------------
 CockroachDB CCL v22.1.3 (x86_64-pc-linux-gnu, built 2022/07/11 14:04:38, go1.17.11)
(1 row)

yadamu=> create table "t_postgres1"."c"(
yadamu(>   "c" character(10485760)
yadamu(> )
yadamu-> ;
CREATE TABLE
yadamu=> insert into t_postgres1.c values (repeat('A',50));
INSERT 0 1
yadamu=> select * from t_postgres1.c
yadamu-> ;
                               c
----------------------------------------------------------------
 %!(BADWIDTH)AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
(1 row)


yadamu=>
```

This is using the cockroach docker image and the following docker-compose file

```
version: '2.4'
services:
  ROACH01-01:
    container_name: ROACH01-01
    image:  cockroachdb/cockroach
    command: start --insecure --store=node1 --join=ROACH01-01,ROACH01-02,ROACH01-03
    mem_limit: '8gb'
    shm_size: '1gb'
    security_opt:
     - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "26257:26257"
      - "8080:8080"
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ROACH01-01-DATA:/cockroach/cockroach-data
    restart: always

  ROACH01-02:
    container_name: ROACH01-02
    image:  cockroachdb/cockroach
    command: start --insecure --store=node2 --join=ROACH01-01,ROACH01-02,ROACH01-03 
    mem_limit: '8gb'
    shm_size: '1gb'
    security_opt:
     - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "26258:26257"
      - "8081:8080"
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ROACH01-02-DATA:/cockroach/cockroach-data
    restart: always

  ROACH01-03:
    container_name: ROACH01-03
    image:  cockroachdb/cockroach
    command: start --insecure --store=node3 --join=ROACH01-01,ROACH01-02,ROACH01-03 
    mem_limit: '8gb'
    shm_size: '1gb'
    security_opt:
     - seccomp:unconfined
    networks:
      - YADAMU-NET
    ports: 
      - "26259:26257"
      - "8082:8080"
    volumes:
      - YADAMU_01-SHARED:/mnt/shared
      - ROACH01-03-DATA:/cockroach/cockroach-data
    restart: always
    
networks: 
  YADAMU-NET:
     name: YADAMU-NET

volumes:
  YADAMU_01-SHARED:
    name: YADAMU_01-SHARED
  ROACH01-01-DATA:
  ROACH01-02-DATA:
  ROACH01-03-DATA:
```
