### ISSUE TITLE
prod: env var set by Kubernetes interferes with server initialization

### ISSUE THREAD

**Issue by patwhite** [cockroachdb/cockroach#8876]
Attempting to run cockroach on kubernetes, and seeing crash. Log file:

```
+ CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)")
++ hostname -f
+ /cockroach/cockroach start --logtostderr --insecure --host cockroach-ktbqx
I160828 16:25:48.273274 cli/start.go:342  CockroachDB beta-20160728-675-g2d7438d (linux amd64, built 2016/08/27 01:22:56, go1.7)
I160828 16:25:48.376600 cli/backtrace.go:40  backtrace disabled: stat /opt/backtrace/bin/ptrace: no such file or directory
I160828 16:25:48.376905 server/context.go:407  1 storage engine initialized
I160828 16:25:48.380121 cli/start.go:362  starting cockroach node
Error: failed to start Cockroach server: unable to resolve RPC address "cockroach-ktbqx:tcp://10.59.253.106:8080": too many colons in address cockroach-ktbqx:tcp://10.59.253.106:8080
Failed running "start"
```

Attempting to run on Google Container Engine, which hosts kubernetes 1.3.5. I've tried numerous different combinations of yaml files and configurations, but this one failed (you need to have a data disk created):

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: cockroach
  labels:
    component: cockroach
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: cockroach
    spec:
      serviceAccount: cockroach
      containers:
      - name: cockroach
        image: cockroachdb/cockroach:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 26257
          name: data
          protocol: TCP
        volumeMounts:
        - mountPath: /cockroach/cockroach-data
          name: data
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)")
            /cockroach/cockroach ${CRARGS[*]}
      volumes:
      - name: data
        # This GCE PD must already exist.
        gcePersistentDisk:
          pdName: cockroach-1-data
          fsType: ext4
```

By all accounts it seems this should work, but not having any luck.
