### ISSUE TITLE
backupccl: create 45TB tpce backup fixture

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#94945]
Full specs for cluster to create the backup:
```
hardware:
  crdb_nodes: 15
  total_nodes: 16
  vol_size: 5000 GBs
  cloud: aws
crdb:
  cluster_name: butler-test-45tb
  crdb_version: v22.2.1
tpce:
  tpce_customers: 2000000
  duration: 24h
backup:
  inc_count: 48
  inc_crontab: */15 * * * *
```
